In [1]:
import numpy as np
import cv2
# creating object 
# opencv-contrib module should be downloaded for running the three models

fgbg1 = cv2.bgsegm.createBackgroundSubtractorMOG();    
fgbg2 = cv2.createBackgroundSubtractorMOG2(); 
fgbg3 = cv2.bgsegm.createBackgroundSubtractorGMG(); 

# capture frames from a camera  
cap = cv2.VideoCapture(0); 
while(1): 
    # read frames 
    ret, img = cap.read(); 
    print(img)  
    # apply mask for background subtraction 
    fgmask1 = fgbg1.apply(img); 
    fgmask2 = fgbg2.apply(img); 
    fgmask3 = fgbg3.apply(img); 
    print(fgmask1)
    cv2.imshow('Original', img); 
    cv2.imshow('MOG', fgmask1); 
    cv2.imshow('MOG2', fgmask2); 
    cv2.imshow('GMG', fgmask3); 
    
    key = cv2.waitKey(1)
    if  key == ord('q'):
        break
cap.release(); 
cv2.destroyAllWindows();

[[[13 28 58]
  [21 35 64]
  [25 39 66]
  ...
  [35 57 51]
  [34 57 49]
  [34 57 49]]

 [[22 37 67]
  [22 36 65]
  [19 33 60]
  ...
  [35 57 51]
  [34 57 49]
  [34 57 49]]

 [[30 34 68]
  [26 28 60]
  [20 23 53]
  ...
  [36 55 51]
  [34 56 50]
  [34 56 50]]

 ...

 [[14 22 19]
  [14 22 19]
  [13 21 18]
  ...
  [14 13 17]
  [14 13 17]
  [14 13 17]]

 [[13 21 30]
  [12 20 29]
  [12 20 27]
  ...
  [14 14 12]
  [14 15 11]
  [14 15 11]]

 [[13 21 30]
  [13 21 30]
  [12 20 27]
  ...
  [13 13 11]
  [13 14 10]
  [13 14 10]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 17  91  92]
  [ 14  82  83]
  [ 22  84  85]
  ...
  [ 88 103  90]
  [ 86  99  84]
  [ 79  92  77]]

 [[ 16  90  91]
  [ 15  83  84]
  [ 25  87  88]
  ...
  [ 87 102  89]
  [ 87 100  85]
  [ 81  94  79]]

 [[ 39  86  92]
  [ 42  82  90]
  [ 52  88  96]
  ...
  [ 79 101  87]
  [ 78 100  84]
  [ 75  97  81]]

 ...

 [[ 35  54  24]
  [ 26  47  25]
  [ 21  

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[45 57 84]
  [34 44 71]
  [42 52 77]
  ...
  [68 72 72]
  [66 73 72]
  [54 61 60]]

 [[48 60 87]
  [39 49 76]
  [44 54 79]
  ...
  [71 75 75]
  [72 79 78]
  [63 70 69]]

 [[44 65 77]
  [39 58 70]
  [43 61 73]
  ...
  [71 78 67]
  [73 80 68]
  [68 75 63]]

 ...

 [[27 12 58]
  [32 18 61]
  [32 21 60]
  ...
  [16 13 25]
  [21 16 28]
  [27 22 34]]

 [[24 12 63]
  [30 18 71]
  [32 20 73]
  ...
  [20 12 19]
  [26 17 24]
  [34 25 32]]

 [[24 12 63]
  [30 18 71]
  [32 20 73]
  ...
  [19 11 18]
  [25 16 23]
  [33 24 31]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[16 65 64]
  [23 62 65]
  [36 68 71]
  ...
  [52 71 59]
  [49 78 65]
  [43 72 59]]

 [[15 64 63]
  [23 62 65]
  [37 69 72]
  ...
  [52 71 59]
  [48 77 64]
  [45 74 61]]

 [[13 62 74]
  [19 60 73]
  [33 66 79]
  ...
  [52 72 54]
  [51 78

[[[ 0 63 77]
  [ 0 63 77]
  [16 63 75]
  ...
  [41 83 63]
  [28 84 51]
  [28 84 51]]

 [[ 0 61 75]
  [ 0 61 75]
  [15 62 74]
  ...
  [39 81 61]
  [27 83 50]
  [27 83 50]]

 [[25 54 82]
  [35 53 77]
  [46 53 74]
  ...
  [65 76 63]
  [57 76 53]
  [59 78 55]]

 ...

 [[38 24 25]
  [33 24 35]
  [23 23 41]
  ...
  [23 15 23]
  [26 14 23]
  [26 14 23]]

 [[32 21 36]
  [26 20 45]
  [19 19 53]
  ...
  [20 15 18]
  [22 15 18]
  [22 15 18]]

 [[35 24 39]
  [27 21 46]
  [19 19 53]
  ...
  [20 15 18]
  [22 15 18]
  [22 15 18]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 0 63 77]
  [ 0 63 77]
  [16 63 75]
  ...
  [41 83 63]
  [28 84 51]
  [28 84 51]]

 [[ 0 61 75]
  [ 0 61 75]
  [15 62 74]
  ...
  [39 81 61]
  [27 83 50]
  [27 83 50]]

 [[25 54 82]
  [35 53 77]
  [46 53 74]
  ...
  [65 76 63]
  [57 76 53]
  [59 78 55]]

 ...

 [[38 24 25]
  [33 24 35]
  [23 23 41]
  ...
  [23 15 23]
  [26 14 23]
  [26 14 23]]

 [[32 21

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[39 51 70]
  [55 65 82]
  [48 59 74]
  ...
  [57 62 59]
  [69 70 66]
  [64 65 61]]

 [[42 54 73]
  [50 60 77]
  [42 53 68]
  ...
  [61 66 63]
  [66 67 63]
  [62 63 59]]

 [[37 55 67]
  [47 60 73]
  [45 56 69]
  ...
  [64 69 66]
  [61 66 62]
  [61 66 62]]

 ...

 [[ 9 13 27]
  [13 17 31]
  [16 20 34]
  ...
  [16 16 18]
  [16 16 18]
  [17 17 19]]

 [[10 12 47]
  [14 14 48]
  [16 16 48]
  ...
  [15 15 15]
  [13 15 15]
  [14 16 16]]

 [[15 17 52]
  [18 18 52]
  [19 19 51]
  ...
  [15 15 15]
  [14 16 16]
  [14 16 16]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[44 61 66]
  [46 63 68]
  [42 59 64]
  ...
  [69 71 73]
  [64 65 71]
  [63 64 70]]

 [[37 54 59]
  [42 59 64]
  [41 58 63]
  ...
  [71 73 75]
  [70 71 77]
  [67 68 74]]

 [[40 52 61]
  [45 57 66]
  [47 59 66]
  ...
  [74 81 78]
  [74 82

[[[25 50 62]
  [31 54 66]
  [37 58 68]
  ...
  [60 68 67]
  [65 72 71]
  [65 72 71]]

 [[31 56 68]
  [32 55 67]
  [36 57 67]
  ...
  [62 70 69]
  [64 71 70]
  [60 67 66]]

 [[29 60 75]
  [27 54 69]
  [32 54 70]
  ...
  [64 72 67]
  [63 69 62]
  [56 62 55]]

 ...

 [[17 20 40]
  [19 20 50]
  [20 19 57]
  ...
  [13 15 15]
  [13 18 15]
  [15 20 17]]

 [[20 25 35]
  [22 25 46]
  [20 22 56]
  ...
  [12 13 29]
  [14 14 32]
  [15 15 33]]

 [[22 27 37]
  [24 27 48]
  [20 22 56]
  ...
  [14 15 31]
  [15 15 33]
  [16 16 34]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[60 58 84]
  [47 50 70]
  [52 64 74]
  ...
  [71 72 48]
  [73 73 43]
  [72 72 42]]

 [[55 53 79]
  [51 54 74]
  [47 59 69]
  ...
  [72 73 49]
  [73 73 43]
  [72 72 42]]

 [[61 49 84]
  [63 56 85]
  [54 56 76]
  ...
  [72 73 51]
  [74 74 48]
  [72 72 46]]

 ...

 [[38 18 34]
  [33 22 41]
  [24 25 47]
  ...
  [ 4 16 15]
  [ 3 17 16]
  [ 4 18 17]]

 [[28 19

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[43 55 90]
  [46 58 87]
  [45 58 81]
  ...
  [63 62 58]
  [64 63 59]
  [68 67 63]]

 [[39 51 86]
  [41 53 82]
  [43 56 79]
  ...
  [59 58 54]
  [64 63 59]
  [72 71 67]]

 [[49 57 64]
  [44 56 63]
  [42 61 66]
  ...
  [61 61 63]
  [62 61 65]
  [65 64 68]]

 ...

 [[28 24 24]
  [25 22 25]
  [19 20 24]
  ...
  [16 13 35]
  [15 13 39]
  [15 13 39]]

 [[36 20 49]
  [32 16 52]
  [26 12 53]
  ...
  [16 13 35]
  [15 13 39]
  [15 13 39]]

 [[39 23 52]
  [35 19 55]
  [28 14 55]
  ...
  [16 13 35]
  [14 12 38]
  [14 12 38]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[43 55 90]
  [46 58 87]
  [45 58 81]
  ...
  [63 62 58]
  [64 63 59]
  [68 67 63]]

 [[39 51 86]
  [41 53 82]
  [43 56 79]
  ...
  [59 58 54]
  [64 63 59]
  [72 71 67]]

 [[49 57 64]
  [44 56 63]
  [42 61 66]
  ...
  [61 61 63]
  [62 61

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[22 69 76]
  [15 55 65]
  [32 65 76]
  ...
  [53 77 63]
  [51 80 57]
  [50 79 56]]

 [[21 68 75]
  [19 59 69]
  [31 64 75]
  ...
  [53 77 63]
  [50 79 56]
  [50 79 56]]

 [[38 62 70]
  [41 61 69]
  [39 58 66]
  ...
  [59 71 70]
  [55 73 65]
  [55 73 65]]

 ...

 [[27 24 28]
  [25 21 28]
  [21 19 27]
  ...
  [15 13 23]
  [14 12 32]
  [16 14 34]]

 [[23 27 37]
  [20 23 37]
  [16 20 37]
  ...
  [17 13 20]
  [18 12 29]
  [20 14 31]]

 [[29 33 43]
  [25 28 42]
  [18 22 39]
  ...
  [16 12 19]
  [17 11 28]
  [18 12 29]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[46 60 77]
  [34 57 71]
  [37 69 80]
  ...
  [61 71 70]
  [50 71 69]
  [46 67 65]]

 [[42 56 73]
  [38 61 75]
  [33 65 76]
  ...
  [59 69 68]
  [50 71 69]
  [48 69 67]]

 [[48 52 63]
  [56 66 75]
  [48 65 71]
  ...
  [59 69 68]
  [55 72

[[[46 59 92]
  [46 60 89]
  [41 56 80]
  ...
  [64 72 65]
  [75 81 74]
  [53 59 52]]

 [[45 58 91]
  [46 60 89]
  [47 62 86]
  ...
  [61 69 62]
  [71 77 70]
  [55 61 54]]

 [[44 58 78]
  [47 61 80]
  [48 63 78]
  ...
  [60 66 59]
  [68 72 65]
  [60 64 57]]

 ...

 [[15 24 17]
  [20 27 24]
  [20 27 26]
  ...
  [30 16 24]
  [29 13 22]
  [28 12 21]]

 [[18 27 29]
  [25 31 34]
  [27 30 34]
  ...
  [37 18 22]
  [42 17 23]
  [36 11 17]]

 [[13 22 24]
  [19 25 28]
  [21 24 28]
  ...
  [39 20 24]
  [45 20 26]
  [36 11 17]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[55 62 73]
  [50 64 73]
  [45 68 72]
  ...
  [46 71 51]
  [46 77 54]
  [47 78 55]]

 [[46 53 64]
  [40 54 63]
  [38 61 65]
  ...
  [41 66 46]
  [44 75 52]
  [47 78 55]]

 [[47 51 67]
  [44 53 64]
  [51 66 72]
  ...
  [41 67 47]
  [47 76 53]
  [50 79 56]]

 ...

 [[23 25 25]
  [24 25 29]
  [22 25 31]
  ...
  [20 14 21]
  [19 13 20]
  [18 12 19]]

 [[18 17

[[[34 62 62]
  [36 58 66]
  [48 65 80]
  ...
  [65 68 72]
  [61 64 70]
  [52 55 61]]

 [[34 62 62]
  [38 60 68]
  [49 66 81]
  ...
  [65 68 72]
  [63 66 72]
  [57 60 66]]

 [[49 52 58]
  [51 53 64]
  [58 59 75]
  ...
  [67 66 72]
  [68 66 74]
  [67 65 73]]

 ...

 [[24 18 44]
  [25 22 46]
  [21 21 41]
  ...
  [ 7 14 35]
  [ 4 13 46]
  [ 4 13 46]]

 [[17 27 36]
  [18 27 38]
  [11 22 35]
  ...
  [21 17 24]
  [18 16 24]
  [18 16 24]]

 [[20 30 39]
  [19 28 39]
  [11 22 35]
  ...
  [20 16 23]
  [17 15 23]
  [16 14 22]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[34 62 62]
  [36 58 66]
  [48 65 80]
  ...
  [65 68 72]
  [61 64 70]
  [52 55 61]]

 [[34 62 62]
  [38 60 68]
  [49 66 81]
  ...
  [65 68 72]
  [63 66 72]
  [57 60 66]]

 [[49 52 58]
  [51 53 64]
  [58 59 75]
  ...
  [67 66 72]
  [68 66 74]
  [67 65 73]]

 ...

 [[24 18 44]
  [25 22 46]
  [21 21 41]
  ...
  [ 7 14 35]
  [ 4 13 46]
  [ 4 13 46]]

 [[17 27

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[52 57 64]
  [58 63 70]
  [49 55 61]
  ...
  [52 68 70]
  [49 69 71]
  [51 71 73]]

 [[52 57 64]
  [56 61 68]
  [55 61 67]
  ...
  [52 68 70]
  [47 67 69]
  [47 67 69]]

 [[45 57 66]
  [46 56 63]
  [49 60 65]
  ...
  [53 66 69]
  [51 67 69]
  [51 67 69]]

 ...

 [[27 24 27]
  [26 21 33]
  [24 19 40]
  ...
  [21  9 44]
  [19  7 48]
  [19  7 48]]

 [[20 18 58]
  [18 18 52]
  [15 18 46]
  ...
  [28 11 34]
  [26 10 39]
  [26 10 39]]

 [[19 17 57]
  [17 17 51]
  [15 18 46]
  ...
  [28 11 34]
  [26 10 39]
  [26 10 39]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[52 57 64]
  [58 63 70]
  [49 55 61]
  ...
  [52 68 70]
  [49 69 71]
  [51 71 73]]

 [[52 57 64]
  [56 61 68]
  [55 61 67]
  ...
  [52 68 70]
  [47 67 69]
  [47 67 69]]

 [[45 57 66]
  [46 56 63]
  [49 60 65]
  ...
  [53 66 69]
  [51 67

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[37 50 88]
  [34 47 78]
  [40 55 78]
  ...
  [59 70 63]
  [59 72 67]
  [59 72 67]]

 [[40 53 91]
  [38 51 82]
  [40 55 78]
  ...
  [58 69 62]
  [58 71 66]
  [58 71 66]]

 [[18 54 90]
  [22 55 84]
  [26 57 76]
  ...
  [49 70 66]
  [48 72 70]
  [48 72 70]]

 ...

 [[22 17 49]
  [28 20 45]
  [30 22 37]
  ...
  [19 14 26]
  [18 15 29]
  [17 14 28]]

 [[ 0 35 31]
  [22 35 40]
  [45 33 44]
  ...
  [21 14 25]
  [19 14 28]
  [18 13 27]]

 [[ 0 37 33]
  [23 36 41]
  [44 32 43]
  ...
  [20 13 24]
  [18 13 27]
  [17 12 26]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[37 50 88]
  [34 47 78]
  [40 55 78]
  ...
  [59 70 63]
  [59 72 67]
  [59 72 67]]

 [[40 53 91]
  [38 51 82]
  [40 55 78]
  ...
  [58 69 62]
  [58 71 66]
  [58 71 66]]

 [[18 54 90]
  [22 55 84]
  [26 57 76]
  ...
  [49 70 66]
  [48 72

[[[36 48 47]
  [41 55 54]
  [48 65 63]
  ...
  [53 62 50]
  [77 87 72]
  [68 78 63]]

 [[44 56 55]
  [43 57 56]
  [49 66 64]
  ...
  [53 62 50]
  [74 84 69]
  [67 77 62]]

 [[51 62 65]
  [46 57 60]
  [50 63 66]
  ...
  [61 64 60]
  [78 79 75]
  [73 74 70]]

 ...

 [[17 21 38]
  [19 20 42]
  [21 19 45]
  ...
  [18 16 16]
  [17 15 15]
  [16 14 14]]

 [[ 6 20 53]
  [10 20 57]
  [12 19 58]
  ...
  [34 14 20]
  [34 14 20]
  [34 14 20]]

 [[ 6 20 53]
  [ 9 19 56]
  [10 17 56]
  ...
  [32 12 18]
  [33 13 19]
  [33 13 19]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[36 48 47]
  [41 55 54]
  [48 65 63]
  ...
  [53 62 50]
  [77 87 72]
  [68 78 63]]

 [[44 56 55]
  [43 57 56]
  [49 66 64]
  ...
  [53 62 50]
  [74 84 69]
  [67 77 62]]

 [[51 62 65]
  [46 57 60]
  [50 63 66]
  ...
  [61 64 60]
  [78 79 75]
  [73 74 70]]

 ...

 [[17 21 38]
  [19 20 42]
  [21 19 45]
  ...
  [18 16 16]
  [17 15 15]
  [16 14 14]]

 [[ 6 20

  [23  8 45]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[48 54 57]
  [47 52 59]
  [50 55 66]
  ...
  [76 71 75]
  [75 66 71]
  [76 67 72]]

 [[52 58 61]
  [49 54 61]
  [49 54 65]
  ...
  [69 64 68]
  [75 66 71]
  [80 71 76]]

 [[55 58 64]
  [59 61 72]
  [66 67 83]
  ...
  [57 57 65]
  [67 63 71]
  [71 67 75]]

 ...

 [[27 22 36]
  [32 23 42]
  [31 22 43]
  ...
  [11 13 33]
  [ 8 13 34]
  [ 8 13 34]]

 [[27 17 43]
  [33 16 48]
  [36 14 48]
  ...
  [15 12 24]
  [13 15 26]
  [13 15 26]]

 [[25 15 41]
  [31 14 46]
  [34 12 46]
  ...
  [14 11 23]
  [13 15 26]
  [14 16 27]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 0 53 66]
  [11 57 69]
  [40 77 88]
  ...
  [50 77 64]
  [43 79 62]
  [42 78 61]]

 [[ 5 58 71]
  [10 56 68]
  [36 73 84]
  ...
  [49 76 63]
  [43 79 62]
  [43 79 62]]

 [[26 67 81]
  [21 56 69]
  [39 69 80]
  ...
  [61 

[[[43 53 70]
  [44 53 66]
  [50 58 67]
  ...
  [59 58 70]
  [66 67 73]
  [60 61 67]]

 [[41 51 68]
  [42 51 64]
  [47 55 64]
  ...
  [60 59 71]
  [66 67 73]
  [62 63 69]]

 [[51 60 63]
  [49 58 60]
  [47 57 54]
  ...
  [64 64 74]
  [69 68 72]
  [67 66 70]]

 ...

 [[25 26 22]
  [25 22 25]
  [24 18 26]
  ...
  [22 11 24]
  [24 13 28]
  [24 13 28]]

 [[27 21 38]
  [23 22 36]
  [18 22 32]
  ...
  [33  9 33]
  [33  9 35]
  [33  9 35]]

 [[23 17 34]
  [23 22 36]
  [22 26 36]
  ...
  [33  9 33]
  [33  9 35]
  [31  7 33]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[32 65 60]
  [30 65 62]
  [29 65 62]
  ...
  [62 76 58]
  [57 76 53]
  [59 78 55]]

 [[27 60 55]
  [27 62 59]
  [31 67 64]
  ...
  [63 77 59]
  [58 77 54]
  [59 78 55]]

 [[21 36 74]
  [24 44 80]
  [32 57 89]
  ...
  [61 83 57]
  [56 82 49]
  [52 78 45]]

 ...

 [[21 16 28]
  [23 17 35]
  [21 16 38]
  ...
  [20 20 30]
  [18 17 29]
  [16 15 27]]

 [[12 18

[[[27 60 57]
  [23 58 61]
  [27 65 72]
  ...
  [74 65 62]
  [82 69 66]
  [81 68 65]]

 [[32 65 62]
  [27 62 65]
  [28 66 73]
  ...
  [75 66 63]
  [82 69 66]
  [81 68 65]]

 [[29 59 68]
  [27 57 68]
  [28 59 73]
  ...
  [72 68 68]
  [75 68 69]
  [74 67 68]]

 ...

 [[19 15 43]
  [22 17 48]
  [23 20 51]
  ...
  [19 22 26]
  [16 22 25]
  [13 19 22]]

 [[14 19 40]
  [14 16 60]
  [12 11 75]
  ...
  [19 17 27]
  [16 16 26]
  [13 13 23]]

 [[17 22 43]
  [15 17 61]
  [ 8  7 71]
  ...
  [18 16 26]
  [17 17 27]
  [15 15 25]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[15 64 67]
  [18 61 67]
  [21 57 65]
  ...
  [71 61 78]
  [72 61 82]
  [70 59 80]]

 [[12 61 64]
  [16 59 65]
  [10 46 54]
  ...
  [72 62 79]
  [71 60 81]
  [69 58 79]]

 [[26 70 72]
  [33 72 75]
  [18 53 56]
  ...
  [65 64 76]
  [64 63 77]
  [60 59 73]]

 ...

 [[30 23 27]
  [29 22 26]
  [26 21 24]
  ...
  [18 21 18]
  [16 21 18]
  [16 21 18]]

 [[28 22

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[39 50 81]
  [36 52 85]
  [25 47 81]
  ...
  [63 71 80]
  [49 67 77]
  [48 66 76]]

 [[40 51 82]
  [30 46 79]
  [32 54 88]
  ...
  [59 67 76]
  [48 66 76]
  [48 66 76]]

 [[49 70 66]
  [36 60 60]
  [46 75 79]
  ...
  [63 71 68]
  [56 73 69]
  [58 75 71]]

 ...

 [[12 20 29]
  [22 23 39]
  [30 23 44]
  ...
  [ 7 19 28]
  [ 5 19 29]
  [ 4 18 28]]

 [[18 23 33]
  [29 23 40]
  [36 21 44]
  ...
  [11 20 25]
  [ 9 19 26]
  [ 7 17 24]]

 [[18 23 33]
  [29 23 40]
  [36 21 44]
  ...
  [12 21 26]
  [ 9 19 26]
  [ 7 17 24]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[43 57 77]
  [48 60 79]
  [31 42 57]
  ...
  [48 72 62]
  [43 72 58]
  [43 72 58]]

 [[43 57 77]
  [46 58 77]
  [35 46 61]
  ...
  [52 76 66]
  [47 76 62]
  [46 75 61]]

 [[40 60 66]
  [35 64 69]
  [28 65 68]
  ...
  [58 78 72]
  [53 77

[[[54 69 65]
  [45 59 68]
  [40 56 76]
  ...
  [59 73 74]
  [71 73 73]
  [71 73 73]]

 [[51 66 62]
  [46 60 69]
  [41 57 77]
  ...
  [61 75 76]
  [73 75 75]
  [72 74 74]]

 [[48 58 65]
  [48 59 74]
  [45 56 79]
  ...
  [63 73 70]
  [70 73 69]
  [70 73 69]]

 ...

 [[18 15 71]
  [20 17 62]
  [20 20 50]
  ...
  [18 19 25]
  [19 18 24]
  [16 15 21]]

 [[ 9 26 56]
  [15 24 57]
  [22 21 57]
  ...
  [14 15 31]
  [14 14 34]
  [12 12 32]]

 [[ 9 26 56]
  [15 24 57]
  [22 21 57]
  ...
  [13 14 30]
  [14 14 34]
  [14 14 34]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[54 69 65]
  [45 59 68]
  [40 56 76]
  ...
  [59 73 74]
  [71 73 73]
  [71 73 73]]

 [[51 66 62]
  [46 60 69]
  [41 57 77]
  ...
  [61 75 76]
  [73 75 75]
  [72 74 74]]

 [[48 58 65]
  [48 59 74]
  [45 56 79]
  ...
  [63 73 70]
  [70 73 69]
  [70 73 69]]

 ...

 [[18 15 71]
  [20 17 62]
  [20 20 50]
  ...
  [18 19 25]
  [19 18 24]
  [16 15 21]]

 [[ 9 26

[[[16 85 89]
  [ 9 60 65]
  [33 66 71]
  ...
  [55 67 66]
  [53 67 68]
  [55 69 70]]

 [[12 81 85]
  [10 61 66]
  [29 62 67]
  ...
  [57 69 68]
  [55 69 70]
  [56 70 71]]

 [[39 61 77]
  [40 52 69]
  [51 55 71]
  ...
  [62 69 71]
  [61 68 71]
  [59 66 69]]

 ...

 [[18 25 28]
  [21 25 36]
  [21 23 43]
  ...
  [16 20 31]
  [18 21 37]
  [14 17 33]]

 [[ 3 26 38]
  [ 6 26 42]
  [ 6 26 44]
  ...
  [20 17 29]
  [23 20 34]
  [20 17 31]]

 [[ 3 26 38]
  [ 6 26 42]
  [ 5 25 43]
  ...
  [18 15 27]
  [21 18 32]
  [19 16 30]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[16 85 89]
  [ 9 60 65]
  [33 66 71]
  ...
  [55 67 66]
  [53 67 68]
  [55 69 70]]

 [[12 81 85]
  [10 61 66]
  [29 62 67]
  ...
  [57 69 68]
  [55 69 70]
  [56 70 71]]

 [[39 61 77]
  [40 52 69]
  [51 55 71]
  ...
  [62 69 71]
  [61 68 71]
  [59 66 69]]

 ...

 [[18 25 28]
  [21 25 36]
  [21 23 43]
  ...
  [16 20 31]
  [18 21 37]
  [14 17 33]]

 [[ 3 26

[[[38 49 94]
  [33 54 92]
  [25 56 87]
  ...
  [51 68 63]
  [55 77 71]
  [53 75 69]]

 [[38 49 94]
  [32 53 91]
  [28 59 90]
  ...
  [52 69 64]
  [55 77 71]
  [53 75 69]]

 [[48 54 79]
  [42 56 75]
  [41 62 74]
  ...
  [58 69 62]
  [64 75 68]
  [62 73 66]]

 ...

 [[13 19 25]
  [16 22 28]
  [18 24 30]
  ...
  [19 16 19]
  [20 17 20]
  [21 18 21]]

 [[32 21 40]
  [29 23 41]
  [23 21 38]
  ...
  [24 16 19]
  [25 17 18]
  [25 17 18]]

 [[30 19 38]
  [27 21 39]
  [22 20 37]
  ...
  [23 15 18]
  [25 17 18]
  [25 17 18]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[45 62 67]
  [33 54 58]
  [40 66 67]
  ...
  [52 73 69]
  [50 73 68]
  [50 73 68]]

 [[42 59 64]
  [38 59 63]
  [37 63 64]
  ...
  [53 74 70]
  [51 74 69]
  [51 74 69]]

 [[50 61 64]
  [51 66 71]
  [41 62 66]
  ...
  [65 74 69]
  [62 73 68]
  [62 73 68]]

 ...

 [[ 4 23 11]
  [22 35 30]
  [29 38 40]
  ...
  [11 18 17]
  [12 20 19]
  [ 9 17 16]]

 [[ 0 24

[[[28 40 49]
  [52 61 72]
  [54 63 76]
  ...
  [58 77 65]
  [57 82 63]
  [46 71 52]]

 [[38 50 59]
  [48 57 68]
  [49 58 71]
  ...
  [58 77 65]
  [56 81 62]
  [46 71 52]]

 [[17 63 80]
  [22 58 76]
  [27 55 74]
  ...
  [58 73 69]
  [58 75 70]
  [51 68 63]]

 ...

 [[24 22 30]
  [24 22 30]
  [27 25 33]
  ...
  [21 16 28]
  [22 14 29]
  [21 13 28]]

 [[23 23 33]
  [23 21 31]
  [27 25 33]
  ...
  [23 18 22]
  [22 16 23]
  [21 15 22]]

 [[24 24 34]
  [26 24 34]
  [32 30 38]
  ...
  [23 18 22]
  [21 15 22]
  [20 14 21]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[28 40 49]
  [52 61 72]
  [54 63 76]
  ...
  [58 77 65]
  [57 82 63]
  [46 71 52]]

 [[38 50 59]
  [48 57 68]
  [49 58 71]
  ...
  [58 77 65]
  [56 81 62]
  [46 71 52]]

 [[17 63 80]
  [22 58 76]
  [27 55 74]
  ...
  [58 73 69]
  [58 75 70]
  [51 68 63]]

 ...

 [[24 22 30]
  [24 22 30]
  [27 25 33]
  ...
  [21 16 28]
  [22 14 29]
  [21 13 28]]

 [[23 23

[[[42 59 79]
  [41 55 74]
  [60 70 87]
  ...
  [55 71 63]
  [46 70 70]
  [47 71 71]]

 [[39 56 76]
  [42 56 75]
  [54 64 81]
  ...
  [60 76 68]
  [50 74 74]
  [48 72 72]]

 [[18 56 63]
  [25 60 64]
  [30 62 65]
  ...
  [64 73 68]
  [55 72 70]
  [53 70 68]]

 ...

 [[20 25 31]
  [18 23 30]
  [17 21 31]
  ...
  [14 13 19]
  [10 13 19]
  [12 15 21]]

 [[21 25 49]
  [19 23 47]
  [17 22 43]
  ...
  [17 11 18]
  [14 13 19]
  [17 16 22]]

 [[16 20 44]
  [14 18 42]
  [13 18 39]
  ...
  [16 10 17]
  [14 13 19]
  [17 16 22]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 61  66 105]
  [ 45  59  92]
  [ 39  64  87]
  ...
  [ 61  59  57]
  [ 73  67  65]
  [ 71  65  63]]

 [[ 55  60  99]
  [ 44  58  91]
  [ 41  66  89]
  ...
  [ 66  64  62]
  [ 73  67  65]
  [ 68  62  60]]

 [[ 52  56  67]
  [ 41  60  68]
  [ 33  67  70]
  ...
  [ 75  65  68]
  [ 77  64  68]
  [ 71  58  62]]

 ...

 [[ 20  16  52]
  [ 21  18  49]
  [ 21  

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[ 25  61  68]
  [ 38  66  74]
  [ 45  65  73]
  ...
  [ 74  74  74]
  [ 72  68  68]
  [ 79  75  75]]

 [[ 24  60  67]
  [ 35  63  71]
  [ 42  62  70]
  ...
  [ 75  75  75]
  [ 72  68  68]
  [ 77  73  73]]

 [[ 24  65  69]
  [ 32  65  70]
  [ 36  61  66]
  ...
  [ 70  75  81]
  [ 63  66  72]
  [ 67  70  76]]

 ...

 [[ 29  24  36]
  [ 33  26  37]
  [ 32  26  34]
  ...
  [ 85  74  71]
  [ 87  76  73]
  [ 90  79  76]]

 [[ 32  24  50]
  [ 31  25  50]
  [ 27  25  45]
  ...
  [101  76  72]
  [107  78  74]
  [111  82  78]]

 [[ 31  23  49]
  [ 30  24  49]
  [ 26  24  44]
  ...
  [101  76  72]
  [107  78  74]
  [109  80  76]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 

  [ 9 20 43]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[41 59 93]
  [23 39 72]
  [40 55 84]
  ...
  [69 72 58]
  [72 74 57]
  [72 74 57]]

 [[35 53 87]
  [29 45 78]
  [50 65 94]
  ...
  [67 70 56]
  [70 72 55]
  [71 73 56]]

 [[25 61 60]
  [29 59 59]
  [48 74 74]
  ...
  [65 70 59]
  [67 72 60]
  [68 73 61]]

 ...

 [[20 23 30]
  [24 26 28]
  [25 26 22]
  ...
  [15 19 29]
  [15 23 32]
  [17 25 34]]

 [[21 19 55]
  [29 25 51]
  [32 26 43]
  ...
  [12 19 40]
  [ 9 20 43]
  [10 21 44]]

 [[19 17 53]
  [30 26 52]
  [36 30 47]
  ...
  [14 21 42]
  [10 21 44]
  [ 9 20 43]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[14 59 80]
  [21 55 72]
  [35 61 70]
  ...
  [77 69 72]
  [78 68 71]
  [75 65 68]]

 [[15 60 81]
  [23 57 74]
  [37 63 72]
  ...
  [80 72 75]
  [82 72 75]
  [79 69 72]]

 [[23 61 79]
  [32 59 74]
  [47 65 75]
  ...
  [75 

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]]
[[[ 6 67 73]
  [ 4 71 76]
  [ 0 68 71]
  ...
  [63 73 72]
  [69 81 80]
  [59 71 70]]

 [[ 8 69 75]
  [ 2 69 74]
  [ 0 70 73]
  ...
  [62 72 71]
  [68 80 79]
  [59 71 70]]

 [[40 64 73]
  [29 60 67]
  [29 68 72]
  ...
  [64 72 69]
  [70 78 75]
  [64 72 69]]

 ...

 [[82 83 69]
  [82 83 71]
  [82 83 71]
  ...
  [16 19 26]
  [16 21 28]
  [18 23 30]]

 [[76 80 73]
  [80 81 75]
  [81 83 75]
  ...
  [27 16 31]
  [28 17 32]
  [29 18 33]]

 [[71 75 68]
  [76 77 71]
  [79 81 73]
  ...
  [27 16 31]
  [27 16 31]
  [26 15 30]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]]
[[[ 45  45  95]
  [ 49  53  88]
  [ 28  35  56]
  ...
  [ 60  76  77]
  [ 61  77  78]
  [ 60  

[[[ 43  49  93]
  [ 50  65 103]
  [ 30  55  88]
  ...
  [ 56  67  72]
  [ 62  77  82]
  [ 59  74  79]]

 [[ 49  55  99]
  [ 47  62 100]
  [ 38  63  96]
  ...
  [ 58  69  74]
  [ 62  77  82]
  [ 53  68  73]]

 [[ 49  58  91]
  [ 40  54  83]
  [ 47  65  89]
  ...
  [ 63  67  69]
  [ 64  70  72]
  [ 50  56  58]]

 ...

 [[ 16  16  34]
  [ 18  18  36]
  [ 17  18  34]
  ...
  [ 17  19  39]
  [ 18  19  43]
  [ 18  19  43]]

 [[ 12  17  37]
  [ 15  18  39]
  [ 17  18  42]
  ...
  [ 21  21  29]
  [ 21  20  32]
  [ 21  20  32]]

 [[ 25  30  50]
  [ 23  26  47]
  [ 20  21  45]
  ...
  [ 21  21  29]
  [ 21  20  32]
  [ 20  19  31]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 43  49  93]
  [ 50  65 103]
  [ 30  55  88]
  ...
  [ 56  67  72]
  [ 62  77  82]
  [ 59  74  79]]

 [[ 49  55  99]
  [ 47  62 100]
  [ 38  63  96]
  ...
  [ 58  69  74]
  [ 62  77  82]
  [ 53  68  73]]

 [[ 49  58  91]
  [ 40  54  83]
  [ 47  65

[[[48 50 85]
  [51 62 93]
  [37 60 83]
  ...
  [71 69 69]
  [66 64 62]
  [71 69 67]]

 [[51 53 88]
  [54 65 96]
  [38 61 84]
  ...
  [67 65 65]
  [70 68 66]
  [79 77 75]]

 [[45 51 86]
  [50 65 95]
  [37 62 85]
  ...
  [70 72 55]
  [75 78 57]
  [79 82 61]]

 ...

 [[28 23 27]
  [25 23 33]
  [20 23 39]
  ...
  [21 16 30]
  [20 16 33]
  [21 17 34]]

 [[19 24 30]
  [18 22 38]
  [15 22 45]
  ...
  [22 20 18]
  [23 22 18]
  [24 23 19]]

 [[18 23 29]
  [19 23 39]
  [14 21 44]
  ...
  [23 21 19]
  [24 23 19]
  [24 23 19]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[48 50 85]
  [51 62 93]
  [37 60 83]
  ...
  [71 69 69]
  [66 64 62]
  [71 69 67]]

 [[51 53 88]
  [54 65 96]
  [38 61 84]
  ...
  [67 65 65]
  [70 68 66]
  [79 77 75]]

 [[45 51 86]
  [50 65 95]
  [37 62 85]
  ...
  [70 72 55]
  [75 78 57]
  [79 82 61]]

 ...

 [[28 23 27]
  [25 23 33]
  [20 23 39]
  ...
  [21 16 30]
  [20 16 33]
  [21 17 34]]

 [[19 24

[[[28 69 93]
  [26 57 78]
  [37 61 79]
  ...
  [73 69 67]
  [76 65 70]
  [78 67 72]]

 [[23 64 88]
  [24 55 76]
  [35 59 77]
  ...
  [72 68 66]
  [75 64 69]
  [83 72 77]]

 [[43 61 87]
  [43 56 79]
  [50 58 75]
  ...
  [80 67 71]
  [81 60 70]
  [91 70 80]]

 ...

 [[32 10 54]
  [22 13 52]
  [14 18 52]
  ...
  [21 20 24]
  [17 20 26]
  [18 21 27]]

 [[75 13 47]
  [50 13 52]
  [26 16 61]
  ...
  [23 22 26]
  [16 22 28]
  [15 21 27]]

 [[77 15 49]
  [50 13 52]
  [24 14 59]
  ...
  [22 21 25]
  [14 20 26]
  [12 18 24]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[27 66 51]
  [35 71 56]
  [47 78 64]
  ...
  [47 71 61]
  [53 80 67]
  [45 72 59]]

 [[32 71 56]
  [39 75 60]
  [48 79 65]
  ...
  [51 75 65]
  [50 77 64]
  [41 68 55]]

 [[37 69 70]
  [44 72 73]
  [51 74 76]
  ...
  [68 81 58]
  [62 78 51]
  [55 71 44]]

 ...

 [[16 29 34]
  [18 29 34]
  [17 28 31]
  ...
  [15 13 39]
  [11 10 42]
  [10  9 41]]

 [[12 22

[[[42 62 80]
  [30 53 76]
  [38 64 92]
  ...
  [55 68 64]
  [62 77 72]
  [61 76 71]]

 [[43 63 81]
  [40 63 86]
  [39 65 93]
  ...
  [51 64 60]
  [55 70 65]
  [56 71 66]]

 [[35 53 69]
  [45 65 83]
  [46 70 88]
  ...
  [63 64 60]
  [66 67 61]
  [70 71 65]]

 ...

 [[97 95 85]
  [93 93 83]
  [94 97 85]
  ...
  [15 17 27]
  [16 17 31]
  [16 17 31]]

 [[93 92 86]
  [90 91 85]
  [93 97 90]
  ...
  [22 14 29]
  [20 13 34]
  [21 14 35]]

 [[85 84 78]
  [84 85 79]
  [91 95 88]
  ...
  [21 13 28]
  [19 12 33]
  [20 13 34]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]]
[[[42 62 80]
  [30 53 76]
  [38 64 92]
  ...
  [55 68 64]
  [62 77 72]
  [61 76 71]]

 [[43 63 81]
  [40 63 86]
  [39 65 93]
  ...
  [51 64 60]
  [55 70 65]
  [56 71 66]]

 [[35 53 69]
  [45 65 83]
  [46 70 88]
  ...
  [63 64 60]
  [66 67 61]
  [70 71 65]]

 ...

 [[97 95 85]
  [93 93 

[[[ 51  54  92]
  [ 48  50  85]
  [ 68  70 102]
  ...
  [ 48  77  72]
  [ 47  78  73]
  [ 48  79  74]]

 [[ 52  55  93]
  [ 53  55  90]
  [ 60  62  94]
  ...
  [ 52  81  76]
  [ 46  77  72]
  [ 41  72  67]]

 [[ 47  57  82]
  [ 50  61  84]
  [ 49  63  82]
  ...
  [ 64  77  73]
  [ 58  73  69]
  [ 53  68  64]]

 ...

 [[ 40  20  47]
  [ 32  22  45]
  [ 20  24  40]
  ...
  [ 23  17  35]
  [ 23  16  38]
  [ 21  14  36]]

 [[  7  18  59]
  [  5  23  56]
  [  0  28  51]
  ...
  [ 19  16  38]
  [ 18  16  42]
  [ 17  15  41]]

 [[  5  16  57]
  [  5  23  56]
  [  3  32  55]
  ...
  [ 18  15  37]
  [ 17  15  41]
  [ 16  14  40]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[33 64 81]
  [35 64 78]
  [27 57 66]
  ...
  [69 65 73]
  [69 62 73]
  [74 67 78]]

 [[29 60 77]
  [35 64 78]
  [35 65 74]
  ...
  [72 68 76]
  [72 65 76]
  [75 68 79]]

 [[33 61 80]
  [38 65 80]
  [39 67 78]
  ...
  [70 73 77]
  [72 73 77]
  [74 7

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[29 68 71]
  [30 65 66]
  [32 67 66]
  ...
  [76 81 78]
  [71 79 74]
  [60 68 63]]

 [[24 63 66]
  [27 62 63]
  [32 67 66]
  ...
  [76 81 78]
  [71 79 74]
  [60 68 63]]

 [[29 73 93]
  [23 63 80]
  [25 62 75]
  ...
  [77 79 81]
  [73 77 77]
  [63 67 67]]

 ...

 [[28 25 28]
  [26 28 30]
  [22 29 28]
  ...
  [87 85 75]
  [87 82 75]
  [86 81 74]]

 [[26 27 33]
  [22 28 35]
  [15 27 36]
  ...
  [94 82 83]
  [96 82 81]
  [96 82 81]]

 [[28 29 35]
  [23 29 36]
  [17 29 38]
  ...
  [94 82 83]
  [96 82 81]
  [96 82 81]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[ 34  60  78]
  [ 39  61  77]
  [ 43  61  76]
  ...
  [ 63  68  75]
  [ 67  72  83]
  [ 72  

[[[18 65 86]
  [32 68 95]
  [20 46 75]
  ...
  [68 80 62]
  [63 77 59]
  [65 79 61]]

 [[17 64 85]
  [31 67 94]
  [25 51 80]
  ...
  [64 76 58]
  [62 76 58]
  [65 79 61]]

 [[35 61 89]
  [40 63 93]
  [35 56 86]
  ...
  [62 70 62]
  [66 75 64]
  [67 76 65]]

 ...

 [[16 19 33]
  [18 20 38]
  [18 21 41]
  ...
  [14 15 21]
  [12 17 23]
  [15 20 26]]

 [[32 17 39]
  [31 18 45]
  [27 20 52]
  ...
  [21 10 29]
  [17 13 31]
  [21 17 35]]

 [[33 18 40]
  [30 17 44]
  [24 17 49]
  ...
  [20  9 28]
  [16 12 30]
  [21 17 35]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[18 65 86]
  [32 68 95]
  [20 46 75]
  ...
  [68 80 62]
  [63 77 59]
  [65 79 61]]

 [[17 64 85]
  [31 67 94]
  [25 51 80]
  ...
  [64 76 58]
  [62 76 58]
  [65 79 61]]

 [[35 61 89]
  [40 63 93]
  [35 56 86]
  ...
  [62 70 62]
  [66 75 64]
  [67 76 65]]

 ...

 [[16 19 33]
  [18 20 38]
  [18 21 41]
  ...
  [14 15 21]
  [12 17 23]
  [15 20 26]]

 [[32 17

[[[53 61 68]
  [55 63 72]
  [50 59 70]
  ...
  [60 75 62]
  [52 67 52]
  [45 60 45]]

 [[54 62 69]
  [55 63 72]
  [51 60 71]
  ...
  [59 74 61]
  [58 73 58]
  [58 73 58]]

 [[35 61 69]
  [37 63 72]
  [36 61 73]
  ...
  [61 73 62]
  [63 76 63]
  [66 79 66]]

 ...

 [[27 19 34]
  [25 20 32]
  [24 22 30]
  ...
  [18 15 19]
  [16 15 19]
  [16 15 19]]

 [[14 17 56]
  [16 20 54]
  [14 22 49]
  ...
  [20 15 18]
  [20 15 18]
  [20 15 18]]

 [[16 19 58]
  [18 22 56]
  [15 23 50]
  ...
  [21 16 19]
  [20 15 18]
  [19 14 17]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[53 61 68]
  [55 63 72]
  [50 59 70]
  ...
  [60 75 62]
  [52 67 52]
  [45 60 45]]

 [[54 62 69]
  [55 63 72]
  [51 60 71]
  ...
  [59 74 61]
  [58 73 58]
  [58 73 58]]

 [[35 61 69]
  [37 63 72]
  [36 61 73]
  ...
  [61 73 62]
  [63 76 63]
  [66 79 66]]

 ...

 [[27 19 34]
  [25 20 32]
  [24 22 30]
  ...
  [18 15 19]
  [16 15 19]
  [16 15 19]]

 [[14 17

[[[ 0 64 40]
  [ 3 65 49]
  [27 80 73]
  ...
  [66 68 68]
  [67 72 69]
  [69 74 71]]

 [[ 1 70 46]
  [13 75 59]
  [27 80 73]
  ...
  [63 65 65]
  [66 71 68]
  [71 76 73]]

 [[11 54 68]
  [27 64 77]
  [32 65 76]
  ...
  [61 68 70]
  [62 72 71]
  [63 73 72]]

 ...

 [[24 21 52]
  [11 21 38]
  [ 4 27 29]
  ...
  [10 18 15]
  [ 9 22 18]
  [13 26 22]]

 [[10 11 57]
  [ 0 13 47]
  [ 0 25 45]
  ...
  [16 17 23]
  [15 20 26]
  [18 23 29]]

 [[19 20 66]
  [ 7 27 61]
  [ 0 42 62]
  ...
  [13 14 20]
  [12 17 23]
  [15 20 26]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 0 64 40]
  [ 3 65 49]
  [27 80 73]
  ...
  [66 68 68]
  [67 72 69]
  [69 74 71]]

 [[ 1 70 46]
  [13 75 59]
  [27 80 73]
  ...
  [63 65 65]
  [66 71 68]
  [71 76 73]]

 [[11 54 68]
  [27 64 77]
  [32 65 76]
  ...
  [61 68 70]
  [62 72 71]
  [63 73 72]]

 ...

 [[24 21 52]
  [11 21 38]
  [ 4 27 29]
  ...
  [10 18 15]
  [ 9 22 18]
  [13 26 22]]

 [[10 11

[[[47 52 90]
  [49 58 89]
  [54 67 91]
  ...
  [61 65 58]
  [73 76 73]
  [72 75 72]]

 [[37 42 80]
  [35 44 75]
  [48 61 85]
  ...
  [63 67 60]
  [61 64 61]
  [60 63 60]]

 [[33 46 70]
  [26 42 62]
  [40 58 73]
  ...
  [59 71 72]
  [44 54 63]
  [46 56 65]]

 ...

 [[19 17 37]
  [22 17 39]
  [23 18 40]
  ...
  [25 16 21]
  [25 16 23]
  [25 16 23]]

 [[23 18 39]
  [26 20 38]
  [27 22 36]
  ...
  [21 17 17]
  [24 17 20]
  [25 18 21]]

 [[25 20 41]
  [29 23 41]
  [29 24 38]
  ...
  [21 17 17]
  [25 18 21]
  [26 19 22]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[47 52 90]
  [49 58 89]
  [54 67 91]
  ...
  [61 65 58]
  [73 76 73]
  [72 75 72]]

 [[37 42 80]
  [35 44 75]
  [48 61 85]
  ...
  [63 67 60]
  [61 64 61]
  [60 63 60]]

 [[33 46 70]
  [26 42 62]
  [40 58 73]
  ...
  [59 71 72]
  [44 54 63]
  [46 56 65]]

 ...

 [[19 17 37]
  [22 17 39]
  [23 18 40]
  ...
  [25 16 21]
  [25 16 23]
  [25 16 23]]

 [[23 18

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[21 53 86]
  [23 50 83]
  [41 62 94]
  ...
  [62 66 76]
  [59 66 77]
  [59 66 77]]

 [[24 56 89]
  [23 50 83]
  [38 59 91]
  ...
  [62 66 76]
  [60 67 78]
  [59 66 77]]

 [[27 59 82]
  [25 52 75]
  [33 56 78]
  ...
  [58 71 76]
  [56 71 77]
  [54 69 75]]

 ...

 [[32 19 32]
  [28 23 35]
  [17 22 33]
  ...
  [30 43 46]
  [22 49 53]
  [17 44 48]]

 [[37 11 44]
  [27 17 50]
  [15 24 57]
  ...
  [56 53 47]
  [43 51 43]
  [41 49 41]]

 [[37 11 44]
  [30 20 53]
  [24 33 66]
  ...
  [54 51 45]
  [36 44 36]
  [44 52 44]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 0 58 83]
  [14 57 81]
  [35 62 84]
  ...
  [66 69 66]
  [68 71 68]
  [69 72 69]]

 [[ 3 61 86]
  [14 57 81]
  [29 56 78]
  ...
  [63 66 63]
  [66 69 66]
  [69 72 69]]

 [[36 63 68]
  [45 62 68]
  [49 58 63]
  ...
  [60 64 66]
  [64 68

[[[44 63 83]
  [44 64 82]
  [38 60 76]
  ...
  [62 68 74]
  [61 73 74]
  [50 62 63]]

 [[44 63 83]
  [42 62 80]
  [38 60 76]
  ...
  [60 66 72]
  [60 72 73]
  [54 66 67]]

 [[28 67 80]
  [25 65 75]
  [22 62 70]
  ...
  [55 78 50]
  [56 82 48]
  [55 81 47]]

 ...

 [[41 18 40]
  [36 17 39]
  [31 19 40]
  ...
  [81 90 78]
  [73 78 75]
  [72 77 74]]

 [[28 19 59]
  [24 20 46]
  [21 23 34]
  ...
  [74 89 76]
  [84 83 79]
  [80 79 75]]

 [[25 16 56]
  [24 20 46]
  [26 28 39]
  ...
  [74 89 76]
  [85 84 80]
  [79 78 74]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[44 63 83]
  [44 64 82]
  [38 60 76]
  ...
  [62 68 74]
  [61 73 74]
  [50 62 63]]

 [[44 63 83]
  [42 62 80]
  [38 60 76]
  ...
  [60 66 72]
  [60 72 73]
  [54 66 67]]

 [[28 67 80]
  [25 65 75]
  [22 62 70]
  ...
  [55 78 50]
  [56 82 48]
  [55 81 47]]

 ...

 [[41 18 40]
  [36 17 

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[ 49  56 104]
  [ 44  55  88]
  [ 59  76  92]
  ...
  [ 64  71  73]
  [ 66  73  76]
  [ 49  56  59]]

 [[ 41  48  96]
  [ 47  58  91]
  [ 55  72  88]
  ...
  [ 63  70  72]
  [ 65  72  75]
  [ 53  60  63]]

 [[ 54  52  88]
  [ 62  62  92]
  [ 53  56  77]
  ...
  [ 52  73  69]
  [ 51  73  71]
  [ 46  68  66]]

 ...

 [[ 16   9  69]
  [ 19  13  68]
  [ 21  18  66]
  ...
  [105 111  93]
  [ 96 110  83]
  [ 99 113  86]]

 [[ 18  17  49]
  [ 16  19  49]
  [ 16  24  51]
  ...
  [127 115  98]
  [127 106  94]
  [130 109  97]]

 [[ 23  22  54]
  [ 18  21  51]
  [ 16  24  51]
  ...
  [123 111  94]
  [126 105  93]
  [131 110  98]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 

[[[ 54  61  81]
  [ 44  55  68]
  [ 47  62  67]
  ...
  [ 63  71  78]
  [ 61  70  75]
  [ 61  70  75]]

 [[ 51  58  78]
  [ 47  58  71]
  [ 50  65  70]
  ...
  [ 63  71  78]
  [ 62  71  76]
  [ 62  71  76]]

 [[ 49  54  60]
  [ 55  62  65]
  [ 56  66  65]
  ...
  [ 62  69  71]
  [ 62  70  69]
  [ 62  70  69]]

 ...

 [[  7  17  16]
  [ 15  22  24]
  [ 19  26  28]
  ...
  [105 113  88]
  [103 109 101]
  [108 114 106]]

 [[ 10   6  41]
  [ 13  15  47]
  [ 11  23  50]
  ...
  [115 120  88]
  [115 122  93]
  [112 119  90]]

 [[ 15  11  46]
  [ 18  20  52]
  [ 14  26  53]
  ...
  [119 124  92]
  [120 127  98]
  [105 112  83]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[ 54  61  81]
  [ 44  55  68]
  [ 47  62  67]
  ...
  [ 63  71  78]
  [ 61  70  75]
  [ 61  70  75]]

 [[ 51  58  78]
  [ 47  58  71]
  [ 50  65  70]
  ...
  [ 63  71  78]
  [ 

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[ 29  52 102]
  [ 34  50  93]
  [ 45  57  92]
  ...
  [ 64  71  74]
  [ 66  71  81]
  [ 55  60  70]]

 [[ 25  48  98]
  [ 30  46  89]
  [ 37  49  84]
  ...
  [ 63  70  73]
  [ 65  70  80]
  [ 58  63  73]]

 [[ 31  58  73]
  [ 38  59  71]
  [ 43  62  70]
  ...
  [ 54  77  57]
  [ 54  79  51]
  [ 51  76  48]]

 ...

 [[ 17  20  34]
  [ 20  19  41]
  [ 21  18  49]
  ...
  [108 131  91]
  [103 132  87]
  [ 90 119  74]]

 [[ 24  16  42]
  [ 24  16  51]
  [ 21  16  56]
  ...
  [114 129  96]
  [111 133  97]
  [102 124  88]]

 [[ 24  16  42]
  [ 24  16  51]
  [ 21  16  56]
  ...
  [113 128  95]
  [112 134  98]
  [109 131  95]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
[[[ 22  62  79]
  [ 38  70  87]
  [ 35  61  79]
  ...
  [ 60  65  62]
  [ 66  66  64]
  [ 71  71  69]]

 [[ 26  66  83]
  [ 36  68  85]
  [ 33  59  77]
  ...
  [ 66  71  68]
  [ 71  71  69]
  [ 72  72  70]]

 [[ 47  67  85]
  [ 48  66  82]
  [ 43  60  75]
  ...
  [ 52  79  74]
  [ 51  81  74]
  [ 47  77  70]]

 ...

 [[ 29  18  33]
  [ 26  17  29]
  [ 25  21  29]
  ...
  [114 114 112]
  [113 110 124]
  [108 105 119]]

 [[ 30  24  22]
  [ 26  21  25]
  [ 25  23  33]
  ...
  [113 121 113]
  [109 115 118]
  [103 109 112]]

 [[ 33  27  25]
  [ 30  25  29]
  [ 30  28  38]
  ...
  [118 126 118]
  [112 118 121]
  [105 111 114]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 47  55  99]
  [ 46  53  83]
  [ 51  58  71]
  ...
  [ 68  71  59]
  [ 72  73  59]
  [ 68  69  55]]

 [[ 44  52  96]
  [ 50  57  87]
  [ 54  61  74]
  ...
  [ 69  72  60]
  [ 72  73  59]
  [ 69  70  56]]

 [[ 42  46  88]
  [ 45  50  80]
  [ 48  54  70]
  ...
  [ 68  71  67]
  [ 69  73  66]
  [ 67  71  64]]

 ...

 [[ 20  24  38]
  [ 24  26  50]
  [ 21  21  53]
  ...
  [106 102  77]
  [129 109  83]
  [152 132 106]]

 [[ 24  22  48]
  [ 28  24  60]
  [ 25  19  64]
  ...
  [101  96  85]
  [118  91  86]
  [136 109 104]]

 [[ 25  23  49]
  [ 28  24  60]
  [ 23  17  62]
  ...
  [107 102  91]
  [113  86  81]
  [119  92  87]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 52  65  80]
  [ 40  63  77]
  [ 30  65  76]
  ...
  [ 55  77  61]
  [ 53  77  61]
  [ 53  77  61]]

 [[ 54  67  82]
  [ 44  67

[[[ 22  60  67]
  [ 37  65  74]
  [ 49  68  80]
  ...
  [ 59  75  67]
  [ 66  86  78]
  [ 48  68  60]]

 [[ 21  59  66]
  [ 33  61  70]
  [ 46  65  77]
  ...
  [ 54  70  62]
  [ 58  78  70]
  [ 46  66  58]]

 [[ 37  69  72]
  [ 37  64  69]
  [ 45  67  75]
  ...
  [ 56  71  67]
  [ 55  74  70]
  [ 50  69  65]]

 ...

 [[  0  23   7]
  [ 16  36  30]
  [ 19  35  37]
  ...
  [ 95 103  86]
  [ 88 100  82]
  [ 93 105  87]]

 [[ 17  24  13]
  [ 27  35  32]
  [ 21  32  37]
  ...
  [ 94 104  87]
  [ 78  98  80]
  [ 63  83  65]]

 [[ 19  26  15]
  [ 27  35  32]
  [ 19  30  35]
  ...
  [102 112  95]
  [ 88 108  90]
  [ 61  81  63]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 56  64  63]
  [ 55  60  66]
  [ 62  66  76]
  ...
  [ 48  67  73]
  [ 50  70  76]
  [ 53  73  79]]

 [[ 54  62  61]
  [ 56  61  67]
  [ 61  65  75]
  ...
  [ 47  66  72]
  [ 49  69  75]
  [ 50  70  76]]

 [[ 51  58  78]
  [ 53  62  75]
  [ 54  65

[[[ 46  58  85]
  [ 47  58  79]
  [ 52  65  80]
  ...
  [ 65  71  73]
  [ 62  68  70]
  [ 60  66  68]]

 [[ 47  59  86]
  [ 50  61  82]
  [ 51  64  79]
  ...
  [ 65  71  73]
  [ 65  71  73]
  [ 65  71  73]]

 [[ 34  62  80]
  [ 39  66  81]
  [ 40  65  77]
  ...
  [ 64  71  68]
  [ 66  73  70]
  [ 67  74  71]]

 ...

 [[ 14  23  54]
  [ 17  30  54]
  [ 12  29  48]
  ...
  [ 92  96  68]
  [ 95  96  64]
  [ 97  98  66]]

 [[ 10  24  65]
  [ 10  28  62]
  [ 10  32  58]
  ...
  [102  87  81]
  [ 97  89  73]
  [104  96  80]]

 [[  3  17  58]
  [  3  21  55]
  [  9  31  57]
  ...
  [104  89  83]
  [102  94  78]
  [118 110  94]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 46  58  85]
  [ 47  58  79]
  [ 52  65  80]
  ...
  [ 65  71  73]
  [ 62  68  70]
  [ 60  66  68]]

 [[ 47  59  86]
  [ 50  61  82]
  [ 51  64  79]
  ...
  [ 65  71  73]
  [ 65  71  73]
  [ 65  71  73]]

 [[ 34  62  80]
  [ 39  66  81]
  [ 40  65

[[[ 34  56  56]
  [ 48  68  70]
  [ 42  61  66]
  ...
  [ 59  71  62]
  [ 59  71  62]
  [ 58  70  61]]

 [[ 38  60  60]
  [ 46  66  68]
  [ 39  58  63]
  ...
  [ 60  72  63]
  [ 59  71  62]
  [ 58  70  61]]

 [[ 42  61  71]
  [ 45  63  75]
  [ 37  55  67]
  ...
  [ 69  70  66]
  [ 70  69  65]
  [ 68  67  63]]

 ...

 [[ 28  28  28]
  [ 29  31  33]
  [ 31  35  37]
  ...
  [127 137 134]
  [ 83  98 103]
  [ 32  47  52]]

 [[ 45  16  61]
  [ 43  23  57]
  [ 43  34  55]
  ...
  [124 129 126]
  [104 110 112]
  [ 51  57  59]]

 [[ 43  14  59]
  [ 39  19  53]
  [ 37  28  49]
  ...
  [123 128 125]
  [132 138 140]
  [ 51  57  59]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 37  70  89]
  [ 21  61  81]
  [ 19  64  85]
  ...
  [ 65  78  65]
  [ 56  69  56]
  [ 56  69  56]]

 [[ 26  59  78]
  [ 18  58  78]
  [ 20  65  86]
  ...
  [ 63  76  63]
  [ 63  76  63]
  [ 65  78  65]]

 [[ 20  54  71]
  [ 21  59  77]
  [ 23  65

[[[21 72 53]
  [21 64 50]
  [34 71 61]
  ...
  [61 64 68]
  [68 70 72]
  [57 59 61]]

 [[16 67 48]
  [30 73 59]
  [27 64 54]
  ...
  [60 63 67]
  [65 67 69]
  [62 64 66]]

 [[ 0 61 59]
  [10 64 63]
  [ 8 54 54]
  ...
  [62 64 64]
  [65 66 62]
  [71 72 68]]

 ...

 [[30 28 28]
  [28 28 30]
  [25 26 30]
  ...
  [54 55 79]
  [51 42 81]
  [34 25 64]]

 [[32 21 52]
  [30 21 52]
  [28 21 52]
  ...
  [70 65 79]
  [41 33 68]
  [19 11 46]]

 [[33 22 53]
  [31 22 53]
  [29 22 53]
  ...
  [90 85 99]
  [39 31 66]
  [15  7 42]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[21 72 53]
  [21 64 50]
  [34 71 61]
  ...
  [61 64 68]
  [68 70 72]
  [57 59 61]]

 [[16 67 48]
  [30 73 59]
  [27 64 54]
  ...
  [60 63 67]
  [65 67 69]
  [62 64 66]]

 [[ 0 61 59]
  [10 64 63]
  [ 8 54 54]
  ...
  [62 64 64]
  [65 66 62]
  [71 72 68]]

 ...

 [[30 28 28]
  [28 28 30]
  [25 26 30]
  ...
  [54 55 79]
  [51 42 81]
  [34 25 64]]

 [[32 21

[[[16 64 66]
  [25 63 63]
  [31 59 59]
  ...
  [74 74 72]
  [74 72 72]
  [77 75 75]]

 [[12 60 62]
  [25 63 63]
  [36 64 64]
  ...
  [70 70 68]
  [71 69 69]
  [74 72 72]]

 [[41 59 69]
  [49 68 76]
  [57 78 82]
  ...
  [61 70 65]
  [63 71 66]
  [63 71 66]]

 ...

 [[16 16 42]
  [19 21 39]
  [15 20 30]
  ...
  [11 32 42]
  [12 47 58]
  [ 0 20 31]]

 [[37 15 61]
  [36 23 52]
  [27 25 35]
  ...
  [13 31 43]
  [33 34 48]
  [21 22 36]]

 [[36 14 60]
  [36 23 52]
  [29 27 37]
  ...
  [15 33 45]
  [23 24 38]
  [22 23 37]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[44 45 67]
  [53 58 78]
  [56 66 83]
  ...
  [68 68 70]
  [65 73 72]
  [72 80 79]]

 [[42 43 65]
  [53 58 78]
  [59 69 86]
  ...
  [68 68 70]
  [57 65 64]
  [58 66 65]]

 [[33 43 60]
  [44 57 72]
  [53 68 81]
  ...
  [56 77 73]
  [46 73 68]
  [47 74 69]]

 ...

 [[22 23 51]
  [18 20 40]
  [15 17 28]
  ...
  [16 21 42]
  [24 24 56]
  [27 27 59]]

 [[19 16

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 43  59  68]
  [ 48  65  71]
  [ 32  51  56]
  ...
  [ 60  68  65]
  [ 64  71  68]
  [ 64  71  68]]

 [[ 39  55  64]
  [ 44  61  67]
  [ 34  53  58]
  ...
  [ 64  72  69]
  [ 67  74  71]
  [ 61  68  65]]

 [[ 28  60  71]
  [ 28  58  67]
  [ 26  54  62]
  ...
  [ 76  69  70]
  [ 84  74  75]
  [ 74  64  65]]

 ...

 [[ 13  17  28]
  [ 17  18  32]
  [ 17  18  32]
  ...
  [114 129 106]
  [130 141 110]
  [120 131 100]]

 [[ 11  20  25]
  [ 15  17  35]
  [ 17  14  45]
  ...
  [129 140 111]
  [129 144 105]
  [119 134  95]]

 [[ 12  21  26]
  [ 15  17  35]
  [ 15  12  43]
  ...
  [141 152 123]
  [128 143 104]
  [118 133  94]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 40  48 106]
  [ 35  42  91]
  [ 46  53  94]
  ...
  [ 65  66  72]
  [ 69  67  75]
  [ 72  70  78]]

 [[ 39  47 105]
  [ 39  46

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 63  49  58]
  [ 52  41  54]
  [ 61  55  72]
  ...
  [ 65  77  78]
  [ 67  81  80]
  [ 58  72  71]]

 [[ 71  57  66]
  [ 57  46  59]
  [ 60  54  71]
  ...
  [ 64  76  77]
  [ 63  77  76]
  [ 54  68  67]]

 [[ 53  66  69]
  [ 50  63  68]
  [ 61  76  82]
  ...
  [ 67  75  72]
  [ 66  75  70]
  [ 58  67  62]]

 ...

 [[ 23  22  34]
  [ 25  23  41]
  [ 22  21  45]
  ...
  [142 133 130]
  [121 108 112]
  [130 117 121]]

 [[ 19  17  57]
  [ 21  20  54]
  [ 20  20  48]
  ...
  [137 128 123]
  [131 122 111]
  [137 128 117]]

 [[ 19  17  57]
  [ 20  19  53]
  [ 20  20  48]
  ...
  [128 119 114]
  [132 123 112]
  [126 117 106]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 63  49  58]
  [ 52  41  54]
  [ 61  55  72]
  ...
  [ 65  77  78]
  [ 67  81  80]
  [ 58  72  71]]

 [[ 71  57  66]
  [ 57  46

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[  0  60  71]
  [ 15  62  72]
  [ 25  61  68]
  ...
  [ 78  73  62]
  [ 81  73  57]
  [ 85  77  61]]

 [[  8  68  79]
  [ 15  62  72]
  [ 21  57  64]
  ...
  [ 77  72  61]
  [ 79  71  55]
  [ 81  73  57]]

 [[ 31  64  71]
  [ 28  55  60]
  [ 30  53  55]
  ...
  [ 72  76  69]
  [ 74  76  68]
  [ 75  77  69]]

 ...

 [[ 10  14  59]
  [ 13  17  59]
  [ 15  21  56]
  ...
  [ 92  90  65]
  [111 107  65]
  [117 113  71]]

 [[  0  11  73]
  [  6  17  72]
  [ 11  21  66]
  ...
  [115  97  87]
  [125  98  84]
  [131 104  90]]

 [[  0  13  75]
  [  8  19  74]
  [ 14  24  69]
  ...
  [108  90  80]
  [ 83  56  42]
  [105  78  64]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 37  63  81]
  [ 46  65  87]
  [ 22  35  59]
  ...
  [ 67  74  73]
  [ 66  73  72]
  [ 65  72  71]]

 [[ 37  63  81]
  [ 40  59

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 41  59 102]
  [ 37  54  84]
  [ 42  59  75]
  ...
  [ 62  75  70]
  [ 57  68  61]
  [ 53  64  57]]

 [[ 36  54  97]
  [ 36  53  83]
  [ 41  58  74]
  ...
  [ 58  71  66]
  [ 58  69  62]
  [ 54  65  58]]

 [[ 26  53  85]
  [ 30  55  77]
  [ 36  61  73]
  ...
  [ 58  70  59]
  [ 60  71  56]
  [ 56  67  52]]

 ...

 [[ 37  17  35]
  [ 35  14  36]
  [ 36  17  40]
  ...
  [ 77  91  59]
  [ 90 104  71]
  [ 81  95  62]]

 [[ 17  14  70]
  [ 15  10  65]
  [ 18  13  63]
  ...
  [ 75  84  73]
  [ 85  92  89]
  [ 81  88  85]]

 [[ 23  20  76]
  [ 19  14  69]
  [ 20  15  65]
  ...
  [ 83  92  81]
  [ 86  93  90]
  [ 87  94  91]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[17 74 61]
  [14 65 54]
  [21 67 59]
  ...
  [63 66 62]
  [64 73 66]
  [60 69 62]]

 [[11 68 55]
  [13 64 53]
  [23 69 61]
  ...

[[[  0  61  61]
  [  0  58  60]
  [ 27  75  81]
  ...
  [ 54  79  59]
  [ 47  79  54]
  [ 37  69  44]]

 [[  5  71  71]
  [  3  61  63]
  [ 19  67  73]
  ...
  [ 52  77  57]
  [ 46  78  53]
  [ 37  69  44]]

 [[  7  57  64]
  [  9  53  63]
  [ 16  56  66]
  ...
  [ 54  78  64]
  [ 53  81  62]
  [ 46  74  55]]

 ...

 [[ 31  22  27]
  [ 32  24  31]
  [ 26  22  30]
  ...
  [103 108 114]
  [ 84  89 100]
  [ 86  91 102]]

 [[ 17  22  33]
  [ 28  21  42]
  [ 37  18  48]
  ...
  [103 114  83]
  [ 92  92  72]
  [ 92  92  72]]

 [[ 20  25  36]
  [ 30  23  44]
  [ 36  17  47]
  ...
  [ 99 110  79]
  [102 102  82]
  [107 107  87]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 24  64  72]
  [ 45  71  79]
  [ 37  49  56]
  ...
  [ 71  71  73]
  [ 71  70  76]
  [ 70  69  75]]

 [[ 23  63  71]
  [ 32  58  66]
  [ 37  49  56]
  ...
  [ 70  70  72]
  [ 72  71  77]
  [ 73  72  78]]

 [[ 23  51  59]
  [ 34  53  61]
  [ 63  73

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 33  60  64]
  [ 34  66  67]
  [ 27  63  62]
  ...
  [ 60  65  85]
  [ 62  64  88]
  [ 64  66  90]]

 [[ 33  60  64]
  [ 34  66  67]
  [ 26  62  61]
  ...
  [ 63  68  88]
  [ 64  66  90]
  [ 63  65  89]]

 [[ 30  57  80]
  [ 34  64  83]
  [ 29  61  76]
  ...
  [ 52  68  77]
  [ 52  70  80]
  [ 47  65  75]]

 ...

 [[ 32  23  18]
  [ 33  26  27]
  [ 27  23  30]
  ...
  [102 118  99]
  [ 88 113  97]
  [ 79 104  88]]

 [[ 19  24  34]
  [ 26  30  46]
  [ 19  24  44]
  ...
  [119 126 114]
  [ 97 119 111]
  [ 93 115 107]]

 [[ 17  22  32]
  [ 26  30  46]
  [ 17  22  42]
  ...
  [125 132 120]
  [102 124 116]
  [ 99 121 113]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 33  60  64]
  [ 34  66  67]
  [ 27  63  62]
  ...
  [ 60  65  85]
  [ 62  64  88]
  [ 64  66  90]]

 [[ 33  60  64]
  [ 34  66

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 29  67  75]
  [ 34  70  77]
  [ 14  51  55]
  ...
  [ 60  70  67]
  [ 57  69  70]
  [ 58  70  71]]

 [[ 28  66  74]
  [ 35  71  78]
  [ 19  56  60]
  ...
  [ 63  73  70]
  [ 59  71  72]
  [ 56  68  69]]

 [[ 41  67  58]
  [ 46  72  63]
  [ 36  62  53]
  ...
  [ 49  75  75]
  [ 45  73  74]
  [ 42  70  71]]

 ...

 [[ 21  26  23]
  [ 21  25  25]
  [ 22  26  28]
  ...
  [109 120 105]
  [105 115 104]
  [ 90 100  89]]

 [[ 28  21  42]
  [ 23  22  36]
  [ 20  25  31]
  ...
  [122 130 123]
  [112 120 117]
  [ 90  98  95]]

 [[ 29  22  43]
  [ 25  24  38]
  [ 21  26  32]
  ...
  [122 130 123]
  [123 131 128]
  [112 120 117]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 19  68  66]
  [ 20  60  60]
  [ 30  62  65]
  ...
  [ 67  81  72]
  [ 68  85  72]
  [ 52  69  56]]

 [[ 14  63  61]
  [ 25  65

[[[ 38  38 110]
  [ 68  72 126]
  [ 46  56  91]
  ...
  [ 59  67  76]
  [ 56  61  71]
  [ 52  57  67]]

 [[ 32  32 104]
  [ 51  55 109]
  [ 43  53  88]
  ...
  [ 60  68  77]
  [ 62  67  77]
  [ 62  67  77]]

 [[ 45  55  90]
  [ 48  61  84]
  [ 48  64  73]
  ...
  [ 56  74  65]
  [ 58  75  62]
  [ 57  74  61]]

 ...

 [[ 39  31  46]
  [ 32  27  38]
  [ 24  25  29]
  ...
  [ 89  94  82]
  [ 98  97  73]
  [ 95  94  70]]

 [[ 42  31  60]
  [ 29  26  48]
  [ 17  24  37]
  ...
  [ 69  85  77]
  [ 62  90  73]
  [ 59  87  70]]

 [[ 40  29  58]
  [ 25  22  44]
  [ 12  19  32]
  ...
  [ 74  90  82]
  [ 76 104  87]
  [ 79 107  90]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 33  53  77]
  [ 43  66  86]
  [ 37  64  78]
  ...
  [ 70  78  61]
  [ 76  85  64]
  [ 51  60  39]]

 [[ 39  59  83]
  [ 42  65  85]
  [ 31  58  72]
  ...
  [ 71  79  62]
  [ 77  86  65]
  [ 59  68  47]]

 [[ 55  62  75]
  [ 58  65  76]
  [ 47  57

[[[ 29  47  39]
  [ 37  55  47]
  [ 56  77  67]
  ...
  [ 60  72  61]
  [ 57  72  59]
  [ 63  78  65]]

 [[ 39  57  49]
  [ 36  54  46]
  [ 54  75  65]
  ...
  [ 63  75  64]
  [ 56  71  58]
  [ 58  73  60]]

 [[ 32  54  48]
  [ 26  48  42]
  [ 45  68  62]
  ...
  [ 66  74  69]
  [ 64  74  65]
  [ 67  77  68]]

 ...

 [[ 40  21  41]
  [ 37  21  40]
  [ 34  20  38]
  ...
  [ 97  83  73]
  [114  85  70]
  [146 117 102]]

 [[ 21  16  56]
  [ 19  17  53]
  [ 18  19  49]
  ...
  [ 94  91  70]
  [ 87  86  58]
  [106 105  77]]

 [[ 17  12  52]
  [ 15  13  49]
  [ 15  16  46]
  ...
  [ 97  94  73]
  [ 90  89  61]
  [104 103  75]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 29  47  39]
  [ 37  55  47]
  [ 56  77  67]
  ...
  [ 60  72  61]
  [ 57  72  59]
  [ 63  78  65]]

 [[ 39  57  49]
  [ 36  54  46]
  [ 54  75  65]
  ...
  [ 63  75  64]
  [ 56  71  58]
  [ 58  73  60]]

 [[ 32  54  48]
  [ 26  48  42]
  [ 45  68

[[[ 29  51  43]
  [ 41  61  62]
  [ 44  63  71]
  ...
  [ 75  71  71]
  [ 73  68  72]
  [ 69  64  68]]

 [[ 40  62  54]
  [ 44  64  65]
  [ 41  60  68]
  ...
  [ 73  69  69]
  [ 71  66  70]
  [ 68  63  67]]

 [[ 48  64  74]
  [ 47  61  78]
  [ 41  57  77]
  ...
  [ 50  73  61]
  [ 50  73  63]
  [ 48  71  61]]

 ...

 [[ 26  19  30]
  [ 21  20  32]
  [ 22  29  40]
  ...
  [ 89  80  69]
  [164 163 149]
  [149 148 134]]

 [[ 28  28  30]
  [ 12  22  31]
  [ 11  31  47]
  ...
  [118  88  69]
  [188 153 132]
  [192 157 136]]

 [[ 48  48  50]
  [ 21  31  40]
  [ 13  33  49]
  ...
  [110  80  61]
  [121  86  65]
  [185 150 129]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0 255 255]
 [  0   0   0 ...   0   0   0]]
[[[ 41  58  64]
  [ 51  67  69]
  [ 59  73  72]
  ...
  [ 61  71  56]
  [ 59  70  55]
  [ 73  84  69]]

 [[ 41  58  64]
  [ 46  62  64]
  [ 50  64  63]
  ...
  [ 63  73  58]
  [ 

[[[ 23  60  64]
  [ 32  57  71]
  [ 38  51  74]
  ...
  [ 60  80  72]
  [ 56  80  70]
  [ 48  72  62]]

 [[ 23  60  64]
  [ 29  54  68]
  [ 39  52  75]
  ...
  [ 59  79  71]
  [ 55  79  69]
  [ 47  71  61]]

 [[ 35  60  65]
  [ 35  52  68]
  [ 44  54  81]
  ...
  [ 66  75  70]
  [ 63  75  64]
  [ 55  67  56]]

 ...

 [[ 20  26  19]
  [ 21  26  22]
  [ 21  26  23]
  ...
  [137 137 109]
  [162 164 126]
  [154 156 118]]

 [[ 26  24  32]
  [ 25  25  33]
  [ 23  26  32]
  ...
  [120 119  91]
  [144 143 105]
  [167 166 128]]

 [[ 33  31  39]
  [ 28  28  36]
  [ 23  26  32]
  ...
  [114 113  85]
  [123 122  84]
  [160 159 121]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 44  47  75]
  [ 50  53  81]
  [ 50  54  79]
  ...
  [ 60  66  83]
  [ 63  67  84]
  [ 65  69  86]]

 [[ 46  49  77]
  [ 49  52  80]
  [ 50  54  79]
  ...
  [ 61  67  84]
  [ 64  68  85]
  [ 64  68  85]]

 [[ 46  53  74]
  [ 47  54  75]
  [ 48  55

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 18  65  51]
  [ 13  60  49]
  [ 22  70  62]
  ...
  [ 61  73  62]
  [ 62  79  66]
  [ 64  81  68]]

 [[ 17  64  50]
  [ 17  64  53]
  [ 23  71  63]
  ...
  [ 63  75  64]
  [ 60  77  64]
  [ 58  75  62]]

 [[ 21  59  59]
  [ 23  62  66]
  [ 21  64  70]
  ...
  [ 66  75  68]
  [ 60  74  65]
  [ 57  71  62]]

 ...

 [[ 23  22  34]
  [ 21  23  34]
  [ 20  24  35]
  ...
  [ 89  90  76]
  [ 83  93  67]
  [149 159 133]]

 [[ 18  13  63]
  [ 18  15  61]
  [ 17  17  59]
  ...
  [103  93  86]
  [ 98  87  82]
  [161 150 145]]

 [[ 17  12  62]
  [ 16  13  59]
  [ 15  15  57]
  ...
  [101  91  84]
  [ 91  80  75]
  [129 118 113]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 18  65  51]
  [ 13  60  49]
  [ 22  70  62]
  ...
  [ 61  73  62]
  [ 62  79  66]
  [ 64  81  68]]

 [[ 17  64  50]
  [ 17  64

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[40 59 71]
  [42 61 73]
  [30 49 61]
  ...
  [65 68 74]
  [67 66 78]
  [68 67 79]]

 [[30 49 61]
  [39 58 70]
  [40 59 71]
  ...
  [61 64 70]
  [65 64 76]
  [69 68 80]]

 [[46 61 67]
  [50 65 71]
  [52 69 75]
  ...
  [54 63 65]
  [58 67 70]
  [66 75 78]]

 ...

 [[12 21 52]
  [11 19 54]
  [10 17 56]
  ...
  [84 84 82]
  [85 82 76]
  [94 91 85]]

 [[19 17 53]
  [13 15 57]
  [ 8 16 61]
  ...
  [91 91 83]
  [90 90 72]
  [98 98 80]]

 [[19 17 53]
  [14 16 58]
  [ 9 17 62]
  ...
  [93 93 85]
  [90 90 72]
  [92 92 74]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[40 59 71]
  [42 61 73]
  [30 49 61]
  ...
  [65 68 74]
  [67 66 78]
  [68 67 79]]

 [[30 49 61]
  [39 58 70]
  [40 59 71]
  ...
  [61 64 70]
  [65 64 76]
  [69 68 80]]

 [[46 61 67]
  [50 65 71]
  [52 69 75]
  ...
  [54 63 65]
  [58 67

[[[23 70 76]
  [21 60 64]
  [21 55 58]
  ...
  [59 74 61]
  [59 70 63]
  [57 68 61]]

 [[18 65 71]
  [23 62 66]
  [25 59 62]
  ...
  [57 72 59]
  [59 70 63]
  [58 69 62]]

 [[ 1 59 68]
  [12 62 71]
  [15 60 67]
  ...
  [61 73 74]
  [54 67 72]
  [50 63 68]]

 ...

 [[27 26 32]
  [25 24 28]
  [23 25 27]
  ...
  [71 98 93]
  [69 97 97]
  [65 93 93]]

 [[27 36 47]
  [22 27 38]
  [20 24 35]
  ...
  [72 96 86]
  [73 95 93]
  [69 91 89]]

 [[34 43 54]
  [23 28 39]
  [17 21 32]
  ...
  [72 96 86]
  [74 96 94]
  [69 91 89]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[23 70 76]
  [21 60 64]
  [21 55 58]
  ...
  [59 74 61]
  [59 70 63]
  [57 68 61]]

 [[18 65 71]
  [23 62 66]
  [25 59 62]
  ...
  [57 72 59]
  [59 70 63]
  [58 69 62]]

 [[ 1 59 68]
  [12 62 71]
  [15 60 67]
  ...
  [61 73 74]
  [54 67 72]
  [50 63 68]]

 ...

 [[27 26 32]
  [25 24 28]
  [23 25 27]
  ...
  [71 98 93]
  [69 97 97]
  [65 93 93]]

 [[27 36

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 19  59  59]
  [ 40  72  75]
  [ 30  55  60]
  ...
  [ 63  68  74]
  [ 64  68  78]
  [ 67  71  81]]

 [[ 24  64  64]
  [ 38  70  73]
  [ 31  56  61]
  ...
  [ 70  75  81]
  [ 65  69  79]
  [ 62  66  76]]

 [[ 31  56  60]
  [ 40  59  65]
  [ 44  56  65]
  ...
  [ 71  78  77]
  [ 68  74  76]
  [ 64  70  72]]

 ...

 [[ 27  15  34]
  [ 28  24  32]
  [ 25  30  26]
  ...
  [105  88  82]
  [109  87  81]
  [124 102  96]]

 [[ 36  16  52]
  [ 31  25  42]
  [ 20  31  26]
  ...
  [104  89  84]
  [111  89  83]
  [122 100  94]]

 [[ 36  16  52]
  [ 32  26  43]
  [ 22  33  28]
  ...
  [104  89  84]
  [111  89  83]
  [119  97  91]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 57  61  77]
  [ 48  61  76]
  [ 36  57  71]
  ...
  [ 54  63  68]
  [ 59  68  73]
  [ 60  69  74]]

 [[ 53  57  73]
  [ 47  60

[[[ 30  54  70]
  [ 36  60  69]
  [ 38  63  67]
  ...
  [ 53  77  63]
  [ 52  76  60]
  [ 52  76  60]]

 [[ 32  56  72]
  [ 36  60  69]
  [ 37  62  66]
  ...
  [ 50  74  60]
  [ 48  72  56]
  [ 48  72  56]]

 [[ 28  55  69]
  [ 32  58  67]
  [ 33  60  65]
  ...
  [ 63  71  66]
  [ 61  69  62]
  [ 61  69  62]]

 ...

 [[ 25  28  25]
  [ 27  29  29]
  [ 26  28  30]
  ...
  [112 121 102]
  [126 135 104]
  [139 148 117]]

 [[ 10  30  24]
  [ 16  33  31]
  [ 17  33  35]
  ...
  [119 128 109]
  [127 142 106]
  [136 151 115]]

 [[  9  29  23]
  [ 16  33  31]
  [ 18  34  36]
  ...
  [130 139 120]
  [128 143 107]
  [123 138 102]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 30  54  70]
  [ 36  60  69]
  [ 38  63  67]
  ...
  [ 53  77  63]
  [ 52  76  60]
  [ 52  76  60]]

 [[ 32  56  72]
  [ 36  60  69]
  [ 37  62  66]
  ...
  [ 50  74  60]
  [ 48  72  56]
  [ 48  72  56]]

 [[ 28  55  69]
  [ 32  58  67]
  [ 33  60

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 26  68  68]
  [ 27  60  65]
  [ 33  59  67]
  ...
  [ 54  76  68]
  [ 55  72  67]
  [ 44  61  56]]

 [[ 21  63  63]
  [ 25  58  63]
  [ 38  64  72]
  ...
  [ 49  71  63]
  [ 55  72  67]
  [ 49  66  61]]

 [[ 55  55  63]
  [ 46  50  60]
  [ 49  57  66]
  ...
  [ 50  69  67]
  [ 56  72  73]
  [ 55  71  72]]

 ...

 [[ 11  18  38]
  [ 19  20  36]
  [ 26  21  32]
  ...
  [ 98  99 103]
  [ 93  92  98]
  [106 105 111]]

 [[ 25  15  50]
  [ 31  16  38]
  [ 39  19  27]
  ...
  [127 119 102]
  [105  90  85]
  [110  95  90]]

 [[ 26  16  51]
  [ 30  15  37]
  [ 37  17  25]
  ...
  [138 130 113]
  [114  99  94]
  [118 103  98]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 31  40  61]
  [ 48  57  78]
  [ 43  53  72]
  ...
  [ 62  69  72]
  [ 58  67  70]
  [ 59  68  71]]

 [[ 43  52  73]
  [ 47  56

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 18  58  78]
  [ 26  60  75]
  [ 36  66  75]
  ...
  [ 65  69  61]
  [ 67  72  60]
  [ 68  73  61]]

 [[ 19  59  79]
  [ 25  59  74]
  [ 33  63  72]
  ...
  [ 65  69  61]
  [ 63  68  56]
  [ 62  67  55]]

 [[ 36  57  89]
  [ 38  56  82]
  [ 42  59  79]
  ...
  [ 63  68  64]
  [ 58  66  58]
  [ 57  65  57]]

 ...

 [[ 18  25  28]
  [ 20  25  32]
  [ 18  22  32]
  ...
  [ 97 104  75]
  [ 99 105  70]
  [ 98 104  69]]

 [[  2  24  30]
  [  8  26  38]
  [ 11  25  44]
  ...
  [100 100  90]
  [101  95  89]
  [ 96  90  84]]

 [[  7  29  35]
  [ 14  32  44]
  [ 17  31  50]
  ...
  [ 94  94  84]
  [ 98  92  86]
  [ 95  89  83]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 49  51  85]
  [ 47  49  83]
  [ 27  29  61]
  ...
  [ 54  70  72]
  [ 50  70  72]
  [ 53  73  75]]

 [[ 49  51  85]
  [ 50  52

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 43  56  59]
  [ 42  59  65]
  [ 37  58  68]
  ...
  [ 59  71  81]
  [ 57  71  81]
  [ 49  63  73]]

 [[ 47  60  63]
  [ 42  59  65]
  [ 43  64  74]
  ...
  [ 59  71  81]
  [ 57  71  81]
  [ 50  64  74]]

 [[ 63  62  66]
  [ 51  56  62]
  [ 53  66  71]
  ...
  [ 62  71  74]
  [ 63  72  75]
  [ 57  66  69]]

 ...

 [[ 28  19  24]
  [ 27  21  18]
  [ 24  22  11]
  ...
  [101 107 100]
  [ 91  98  95]
  [ 89  96  93]]

 [[ 37   6  69]
  [ 36  15  47]
  [ 32  23  21]
  ...
  [110 108  97]
  [ 90 106  80]
  [ 88 104  78]]

 [[ 40   9  72]
  [ 40  19  51]
  [ 38  29  27]
  ...
  [111 109  98]
  [ 91 107  81]
  [ 89 105  79]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 36  56  57]
  [ 48  66  68]
  [ 50  68  70]
  ...
  [ 67  74  71]
  [ 62  71  66]
  [ 57  66  61]]

 [[ 34  54  55]
  [ 48  66

[[[ 56  61  81]
  [ 51  61  78]
  [ 41  59  71]
  ...
  [ 61  71  68]
  [ 58  70  69]
  [ 57  69  68]]

 [[ 52  57  77]
  [ 50  60  77]
  [ 42  60  72]
  ...
  [ 60  70  67]
  [ 58  70  69]
  [ 57  69  68]]

 [[ 60  63  79]
  [ 61  65  79]
  [ 46  55  66]
  ...
  [ 63  72  65]
  [ 63  73  64]
  [ 63  73  64]]

 ...

 [[ 23  22  26]
  [ 24  25  31]
  [ 21  26  32]
  ...
  [136 146 131]
  [130 145 132]
  [134 149 136]]

 [[ 22  24  34]
  [ 19  29  38]
  [ 11  31  39]
  ...
  [143 151 118]
  [139 151 118]
  [141 153 120]]

 [[ 28  30  40]
  [ 23  33  42]
  [ 13  33  41]
  ...
  [142 150 117]
  [141 153 120]
  [143 155 122]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 56  61  81]
  [ 51  61  78]
  [ 41  59  71]
  ...
  [ 61  71  68]
  [ 58  70  69]
  [ 57  69  68]]

 [[ 52  57  77]
  [ 50  60  77]
  [ 42  60  72]
  ...
  [ 60  70  67]
  [ 58  70  69]
  [ 57  69  68]]

 [[ 60  63  79]
  [ 61  65  79]
  [ 46  55

[[[ 19  60  73]
  [ 27  64  75]
  [ 27  61  68]
  ...
  [ 69  72  69]
  [ 76  67  64]
  [ 76  67  64]]

 [[ 24  65  78]
  [ 24  61  72]
  [ 28  62  69]
  ...
  [ 67  70  67]
  [ 76  67  64]
  [ 78  69  66]]

 [[ 33  60  83]
  [ 30  55  77]
  [ 37  60  80]
  ...
  [ 62  67  64]
  [ 71  68  64]
  [ 73  70  66]]

 ...

 [[ 23  15  32]
  [ 27  22  44]
  [ 29  29  55]
  ...
  [ 97  88  75]
  [ 99  86  63]
  [112  99  76]]

 [[ 13  20  40]
  [ 20  26  53]
  [ 24  30  65]
  ...
  [ 97  81  79]
  [100  80  64]
  [111  91  75]]

 [[ 15  22  42]
  [ 19  25  52]
  [ 20  26  61]
  ...
  [103  87  85]
  [101  81  65]
  [106  86  70]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 19  60  73]
  [ 27  64  75]
  [ 27  61  68]
  ...
  [ 69  72  69]
  [ 76  67  64]
  [ 76  67  64]]

 [[ 24  65  78]
  [ 24  61  72]
  [ 28  62  69]
  ...
  [ 67  70  67]
  [ 76  67  64]
  [ 78  69  66]]

 [[ 33  60  83]
  [ 30  55  77]
  [ 37  60

[[[ 51  57  60]
  [ 55  64  67]
  [ 47  63  65]
  ...
  [ 73  66  67]
  [ 73  67  65]
  [ 73  67  65]]

 [[ 55  61  64]
  [ 50  59  62]
  [ 48  64  66]
  ...
  [ 76  69  70]
  [ 76  70  68]
  [ 75  69  67]]

 [[ 59  64  70]
  [ 48  57  62]
  [ 54  67  72]
  ...
  [ 73  71  71]
  [ 72  72  70]
  [ 73  73  71]]

 ...

 [[ 26  23  35]
  [ 25  28  34]
  [ 22  30  29]
  ...
  [ 87  97  88]
  [ 85  93  86]
  [ 78  86  79]]

 [[ 12  18  43]
  [ 14  32  42]
  [  7  36  31]
  ...
  [ 77 101  85]
  [ 88  94  87]
  [ 83  89  82]]

 [[ 10  16  41]
  [ 17  35  45]
  [ 10  39  34]
  ...
  [ 78 102  86]
  [ 88  94  87]
  [ 87  93  86]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 51  57  60]
  [ 55  64  67]
  [ 47  63  65]
  ...
  [ 73  66  67]
  [ 73  67  65]
  [ 73  67  65]]

 [[ 55  61  64]
  [ 50  59  62]
  [ 48  64  66]
  ...
  [ 76  69  70]
  [ 76  70  68]
  [ 75  69  67]]

 [[ 59  64  70]
  [ 48  57  62]
  [ 54  67

[[[ 16  57 103]
  [ 25  57 100]
  [ 31  55  92]
  ...
  [ 63  73  64]
  [ 61  71  56]
  [ 61  71  56]]

 [[ 14  55 101]
  [ 25  57 100]
  [ 34  58  95]
  ...
  [ 63  73  64]
  [ 63  73  58]
  [ 64  74  59]]

 [[ 28  57  85]
  [ 32  61  84]
  [ 35  65  84]
  ...
  [ 69  69  69]
  [ 72  71  65]
  [ 73  72  66]]

 ...

 [[ 33  24  21]
  [ 29  22  23]
  [ 25  22  25]
  ...
  [136 135 111]
  [137 135 101]
  [138 136 102]]

 [[ 27  19  27]
  [ 33  25  42]
  [ 26  19  41]
  ...
  [150 128 122]
  [159 130 115]
  [170 141 126]]

 [[ 30  22  30]
  [ 44  36  53]
  [ 33  26  48]
  ...
  [141 119 113]
  [155 126 111]
  [173 144 129]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 16  57 103]
  [ 25  57 100]
  [ 31  55  92]
  ...
  [ 63  73  64]
  [ 61  71  56]
  [ 61  71  56]]

 [[ 14  55 101]
  [ 25  57 100]
  [ 34  58  95]
  ...
  [ 63  73  64]
  [ 63  73  58]
  [ 64  74  59]]

 [[ 28  57  85]
  [ 32  61  84]
  [ 35  65

[[[ 51  54  75]
  [ 43  56  79]
  [ 29  52  75]
  ...
  [ 56  71  66]
  [ 61  75  67]
  [ 65  79  71]]

 [[ 50  53  74]
  [ 47  60  83]
  [ 38  61  84]
  ...
  [ 59  74  69]
  [ 63  77  69]
  [ 66  80  72]]

 [[ 55  62  85]
  [ 53  63  90]
  [ 45  60  89]
  ...
  [ 62  70  67]
  [ 63  71  66]
  [ 64  72  67]]

 ...

 [[ 29  27  27]
  [ 27  26  32]
  [ 24  23  35]
  ...
  [132 141 122]
  [116 127 114]
  [ 90 101  88]]

 [[ 42  26  55]
  [ 36  24  47]
  [ 28  25  39]
  ...
  [138 136 125]
  [117 125 110]
  [ 96 104  89]]

 [[ 32  16  45]
  [ 26  14  37]
  [ 22  19  33]
  ...
  [146 144 133]
  [130 138 123]
  [115 123 108]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 40  58  73]
  [ 43  57  76]
  [ 48  59  80]
  ...
  [ 59  75  56]
  [ 58  77  55]
  [ 63  82  60]]

 [[ 43  61  76]
  [ 44  58  77]
  [ 51  62  83]
  ...
  [ 57  73  54]
  [ 57  76  54]
  [ 61  80  58]]

 [[ 46  63  68]
  [ 36  58  64]
  [ 33  61

[[[ 47  65 109]
  [ 36  53  93]
  [ 37  55  89]
  ...
  [ 66  72  74]
  [ 70  71  77]
  [ 69  70  76]]

 [[ 36  54  98]
  [ 33  50  90]
  [ 36  54  88]
  ...
  [ 68  74  76]
  [ 70  71  77]
  [ 69  70  76]]

 [[ 39  54  78]
  [ 42  56  76]
  [ 45  59  76]
  ...
  [ 80  75  68]
  [ 81  72  67]
  [ 79  70  65]]

 ...

 [[ 23  24  38]
  [ 24  27  33]
  [ 22  27  24]
  ...
  [ 74  81  78]
  [ 65  71  64]
  [134 140 133]]

 [[ 22  33  26]
  [ 23  33  32]
  [ 20  31  36]
  ...
  [ 85  83  81]
  [ 83  78  71]
  [120 115 108]]

 [[ 24  35  28]
  [ 26  36  35]
  [ 22  33  38]
  ...
  [ 90  88  86]
  [ 82  77  70]
  [ 91  86  79]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[43 64 62]
  [48 63 76]
  [48 58 85]
  ...
  [76 68 71]
  [75 68 65]
  [76 69 66]]

 [[42 63 61]
  [48 63 76]
  [49 59 86]
  ...
  [74 66 69]
  [75 68 65]
  [77 70 67]]

 [[51 59 66]
  [53 61 78]
  [50 58 85]
  ...
  [67 70 66]
  [69 74 63]
  [71 7

[[[ 38  52  85]
  [ 37  50  73]
  [ 52  65  78]
  ...
  [ 62  69  66]
  [ 58  65  64]
  [ 68  75  74]]

 [[ 39  53  86]
  [ 35  48  71]
  [ 50  63  76]
  ...
  [ 65  72  69]
  [ 60  67  66]
  [ 68  75  74]]

 [[ 41  64  86]
  [ 38  59  73]
  [ 48  69  73]
  ...
  [ 65  80  67]
  [ 55  69  61]
  [ 55  69  61]]

 ...

 [[ 17  29  30]
  [ 19  27  26]
  [ 20  25  22]
  ...
  [101 113  95]
  [ 82  98  80]
  [ 72  88  70]]

 [[ 30  17  46]
  [ 23  24  40]
  [ 15  29  30]
  ...
  [116 117 105]
  [ 92 102  91]
  [ 81  91  80]]

 [[ 29  16  45]
  [ 24  25  41]
  [ 18  32  33]
  ...
  [132 133 121]
  [110 120 109]
  [ 93 103  92]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 48  57  70]
  [ 53  63  72]
  [ 51  62  67]
  ...
  [ 57  67  64]
  [ 58  71  66]
  [ 62  75  70]]

 [[ 50  59  72]
  [ 50  60  69]
  [ 47  58  63]
  ...
  [ 60  70  67]
  [ 59  72  67]
  [ 62  75  70]]

 [[ 44  62  64]
  [ 45  61  63]
  [ 46  60

[[[ 44  62  64]
  [ 45  58  61]
  [ 40  51  54]
  ...
  [ 70  68  68]
  [ 60  70  69]
  [ 61  71  70]]

 [[ 48  66  68]
  [ 48  61  64]
  [ 48  59  62]
  ...
  [ 70  68  68]
  [ 60  70  69]
  [ 59  69  68]]

 [[ 37  60  72]
  [ 35  56  68]
  [ 39  58  68]
  ...
  [ 62  71  74]
  [ 55  73  74]
  [ 54  72  73]]

 ...

 [[ 20  32  33]
  [ 26  29  33]
  [ 32  27  31]
  ...
  [ 94  91  85]
  [ 84  78  75]
  [ 92  86  83]]

 [[ 13  26  39]
  [ 26  28  39]
  [ 35  26  37]
  ...
  [ 95  94  98]
  [ 79  79  87]
  [ 65  65  73]]

 [[  8  21  34]
  [ 22  24  35]
  [ 34  25  36]
  ...
  [115 114 118]
  [ 95  95 103]
  [ 58  58  66]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 44  62  64]
  [ 45  58  61]
  [ 40  51  54]
  ...
  [ 70  68  68]
  [ 60  70  69]
  [ 61  71  70]]

 [[ 48  66  68]
  [ 48  61  64]
  [ 48  59  62]
  ...
  [ 70  68  68]
  [ 60  70  69]
  [ 59  69  68]]

 [[ 37  60  72]
  [ 35  56  68]
  [ 39  58

[[[32 67 78]
  [28 62 70]
  [12 47 51]
  ...
  [60 75 71]
  [60 76 68]
  [56 72 64]]

 [[25 60 71]
  [23 57 65]
  [15 50 54]
  ...
  [60 75 71]
  [60 76 68]
  [54 70 62]]

 [[22 64 66]
  [26 66 65]
  [31 70 64]
  ...
  [59 75 66]
  [60 77 65]
  [52 69 57]]

 ...

 [[36 18 27]
  [38 19 31]
  [35 18 30]
  ...
  [79 92 87]
  [68 81 84]
  [34 47 50]]

 [[31 24 27]
  [34 23 40]
  [33 18 50]
  ...
  [70 88 89]
  [62 82 84]
  [38 58 60]]

 [[30 23 26]
  [32 21 38]
  [29 14 46]
  ...
  [78 96 97]
  [52 72 74]
  [28 48 50]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 58  69  74]
  [ 47  58  63]
  [ 50  63  66]
  ...
  [ 65  69  71]
  [ 65  68  72]
  [ 64  67  71]]

 [[ 58  69  74]
  [ 44  55  60]
  [ 56  69  72]
  ...
  [ 65  69  71]
  [ 65  68  72]
  [ 64  67  71]]

 [[ 33  67  84]
  [ 19  51  66]
  [ 40  71  85]
  ...
  [ 72  69  72]
  [ 71  68  71]
  [ 70  67  70]]

 ...

 [[ 30  22  30]
  [ 25  23  31]
  [ 19  

[[[  9  63  52]
  [ 25  69  61]
  [ 28  61  56]
  ...
  [ 63  70  67]
  [ 64  73  68]
  [ 67  76  71]]

 [[ 16  70  59]
  [ 25  69  61]
  [ 30  63  58]
  ...
  [ 57  64  61]
  [ 61  70  65]
  [ 68  77  72]]

 [[ 30  65  69]
  [ 34  61  66]
  [ 40  61  65]
  ...
  [ 63  71  68]
  [ 65  73  70]
  [ 68  76  73]]

 ...

 [[ 12  30  31]
  [ 12  29  35]
  [ 16  31  44]
  ...
  [113 118 107]
  [113 126 113]
  [109 122 109]]

 [[ 18  35  40]
  [ 18  33  39]
  [ 20  35  41]
  ...
  [113 116  95]
  [109 125 107]
  [109 125 107]]

 [[ 16  33  38]
  [ 15  30  36]
  [ 17  32  38]
  ...
  [117 120  99]
  [114 130 112]
  [116 132 114]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 15  61  73]
  [ 23  65  75]
  [ 31  69  77]
  ...
  [ 87  69  57]
  [102  73  59]
  [102  73  59]]

 [[ 22  68  80]
  [ 27  69  79]
  [ 33  71  79]
  ...
  [ 86  68  56]
  [ 99  70  56]
  [ 98  69  55]]

 [[ 23  68  66]
  [ 27  67  66]
  [ 28  66

[[[38 57 79]
  [26 50 68]
  [34 64 75]
  ...
  [66 73 70]
  [66 69 66]
  [69 72 69]]

 [[37 56 78]
  [29 53 71]
  [40 70 81]
  ...
  [65 72 69]
  [65 68 65]
  [66 69 66]]

 [[ 9 69 71]
  [ 8 63 66]
  [17 70 73]
  ...
  [54 75 65]
  [49 72 62]
  [51 74 64]]

 ...

 [[20 20 40]
  [19 18 42]
  [16 16 44]
  ...
  [34 22 33]
  [52 27 46]
  [56 31 50]]

 [[28 15 54]
  [28 16 51]
  [29 18 49]
  ...
  [27 29 39]
  [31 21 38]
  [42 32 49]]

 [[27 14 53]
  [28 16 51]
  [28 17 48]
  ...
  [41 43 53]
  [27 17 34]
  [36 26 43]]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 255   0   0]
 [  0   0   0 ... 255 255   0]
 [  0   0   0 ...   0 255   0]]
[[[ 19  68  66]
  [ 14  53  57]
  [ 28  60  69]
  ...
  [ 65  69  71]
  [ 67  68  72]
  [ 67  68  72]]

 [[ 21  70  68]
  [ 23  62  66]
  [ 36  68  77]
  ...
  [ 65  69  71]
  [ 68  69  73]
  [ 67  68  72]]

 [[ 31  57  66]
  [ 33  56  68]
  [ 40  63  77]
  ...
  [ 70  70  68]
  [ 72  

[[[26 58 69]
  [27 57 68]
  [28 56 65]
  ...
  [44 77 66]
  [45 81 66]
  [46 82 67]]

 [[22 54 65]
  [27 57 68]
  [28 56 65]
  ...
  [46 79 68]
  [44 80 65]
  [43 79 64]]

 [[10 58 65]
  [18 63 70]
  [19 60 66]
  ...
  [58 73 68]
  [54 72 64]
  [51 69 61]]

 ...

 [[31 23 40]
  [31 25 42]
  [29 25 42]
  ...
  [81 90 78]
  [81 92 73]
  [75 86 67]]

 [[35 21 64]
  [35 21 64]
  [34 20 61]
  ...
  [75 66 71]
  [76 85 78]
  [68 77 70]]

 [[39 25 68]
  [38 24 67]
  [36 22 63]
  ...
  [73 64 69]
  [75 84 77]
  [79 88 81]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[26 58 69]
  [27 57 68]
  [28 56 65]
  ...
  [44 77 66]
  [45 81 66]
  [46 82 67]]

 [[22 54 65]
  [27 57 68]
  [28 56 65]
  ...
  [46 79 68]
  [44 80 65]
  [43 79 64]]

 [[10 58 65]
  [18 63 70]
  [19 60 66]
  ...
  [58 73 68]
  [54 72 64]
  [51 69 61]]

 ...

 [[31 23 40]
  [31 25 42]
  [29 25 42]
  ...
  [81 90 78]
  [81 92 73]
  [75 86 67]]

 [[35 21

[[[  6  43  84]
  [ 27  62 101]
  [ 36  70 106]
  ...
  [ 34  11  21]
  [ 36  12  22]
  [ 34  10  20]]

 [[ 11  48  89]
  [ 21  56  95]
  [ 34  68 104]
  ...
  [ 34  11  21]
  [ 36  12  22]
  [ 34  10  20]]

 [[ 49  75  73]
  [ 48  71  73]
  [ 62  83  87]
  ...
  [ 33  13  19]
  [ 35  13  19]
  [ 34  12  18]]

 ...

 [[ 12   7  49]
  [ 19  12  52]
  [ 21  13  49]
  ...
  [ 99 105  98]
  [ 92  99  88]
  [ 88  95  84]]

 [[ 20  14  84]
  [ 28  23  79]
  [ 30  27  69]
  ...
  [105 106  92]
  [ 98 101  79]
  [ 89  92  70]]

 [[ 14   8  78]
  [ 23  18  74]
  [ 26  23  65]
  ...
  [109 110  96]
  [102 105  83]
  [ 90  93  71]]]
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[[  6  43  84]
  [ 27  62 101]
  [ 36  70 106]
  ...
  [ 34  11  21]
  [ 36  12  22]
  [ 34  10  20]]

 [[ 11  48  89]
  [ 21  56  95]
  [ 34  68 104]
  ...
  [ 34  11  21]
  [ 

[[[  9  65  85]
  [ 14  54  74]
  [ 31  57  76]
  ...
  [ 18  14  12]
  [ 19  16  12]
  [ 20  17  13]]

 [[  2  58  78]
  [ 19  59  79]
  [ 30  56  75]
  ...
  [ 18  14  12]
  [ 19  16  12]
  [ 19  16  12]]

 [[ 18  63  70]
  [ 32  68  76]
  [ 32  62  71]
  ...
  [ 21  14  12]
  [ 23  14  12]
  [ 23  14  12]]

 ...

 [[ 23  29  31]
  [ 22  27  33]
  [ 19  23  33]
  ...
  [ 82  89  77]
  [ 96 100  82]
  [ 96 100  82]]

 [[ 23  16  45]
  [ 24  17  48]
  [ 23  16  48]
  ...
  [ 94  91  71]
  [ 94 104  69]
  [ 96 106  71]]

 [[ 26  19  48]
  [ 28  21  52]
  [ 27  20  52]
  ...
  [ 94  91  71]
  [ 93 103  68]
  [ 96 106  71]]]
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[[  9  65  85]
  [ 14  54  74]
  [ 31  57  76]
  ...
  [ 18  14  12]
  [ 19  16  12]
  [ 20  17  13]]

 [[  2  58  78]
  [ 19  59  79]
  [ 30  56  75]
  ...
  [ 18  14  12]
  [ 

[[[ 0 68 97]
  [10 62 81]
  [25 59 66]
  ...
  [37 17 16]
  [38 20 19]
  [39 21 20]]

 [[ 0 65 94]
  [ 8 60 79]
  [32 66 73]
  ...
  [38 18 17]
  [38 20 19]
  [39 21 20]]

 [[ 2 63 69]
  [16 64 71]
  [32 68 75]
  ...
  [32 20 13]
  [33 21 12]
  [33 21 12]]

 ...

 [[20 19 43]
  [20 22 42]
  [22 26 42]
  ...
  [71 75 68]
  [69 72 68]
  [68 71 67]]

 [[30 22 39]
  [26 24 41]
  [23 27 43]
  ...
  [63 74 55]
  [62 73 54]
  [62 73 54]]

 [[31 23 40]
  [25 23 40]
  [21 25 41]
  ...
  [57 68 49]
  [62 73 54]
  [68 79 60]]]
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[[ 0 68 97]
  [10 62 81]
  [25 59 66]
  ...
  [37 17 16]
  [38 20 19]
  [39 21 20]]

 [[ 0 65 94]
  [ 8 60 79]
  [32 66 73]
  ...
  [38 18 17]
  [38 20 19]
  [39 21 20]]

 [[ 2 63 69]
  [16 64 71]
  [32 68 75]
  ...
  [32 20 13]
  [33 21 12]
  [33 21 12]]

 ...

 [[20 19 43]
  [20 22 

[[[42 57 87]
  [42 51 84]
  [42 46 80]
  ...
  [23 24 28]
  [24 27 33]
  [25 28 34]]

 [[34 49 79]
  [42 51 84]
  [45 49 83]
  ...
  [23 24 28]
  [23 26 32]
  [23 26 32]]

 [[57 52 64]
  [56 57 71]
  [53 60 73]
  ...
  [23 24 28]
  [24 25 29]
  [23 24 28]]

 ...

 [[15 13 49]
  [23 18 57]
  [24 19 59]
  ...
  [85 93 76]
  [75 87 64]
  [66 78 55]]

 [[19  4 78]
  [30 14 85]
  [31 16 83]
  ...
  [92 91 75]
  [85 81 71]
  [76 72 62]]

 [[19  4 78]
  [27 11 82]
  [25 10 77]
  ...
  [82 81 65]
  [80 76 66]
  [75 71 61]]]
[[  0   0   0 ... 255 255   0]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[[42 63 65]
  [38 58 59]
  [46 67 63]
  ...
  [50 76 66]
  [50 74 62]
  [48 72 60]]

 [[39 60 62]
  [36 56 57]
  [46 67 63]
  ...
  [51 77 67]
  [51 75 63]
  [48 72 60]]

 [[41 66 70]
  [37 58 60]
  [43 62 60]
  ...
  [60 73 78]
  [58 71 74]
  [55 68 71]]

 ...

 [[13 22 17]
  [18 26 

[[[29 64 63]
  [44 67 71]
  [46 61 67]
  ...
  [18 44 45]
  [ 1 33 34]
  [ 0 21 22]]

 [[31 66 65]
  [41 64 68]
  [45 60 66]
  ...
  [25 51 52]
  [11 43 44]
  [ 0 23 24]]

 [[47 66 74]
  [39 63 72]
  [33 63 72]
  ...
  [24 44 36]
  [17 40 32]
  [ 0 20 12]]

 ...

 [[19 24 30]
  [21 23 33]
  [20 22 33]
  ...
  [73 89 71]
  [69 95 71]
  [67 93 69]]

 [[26 18 43]
  [29 17 50]
  [28 15 54]
  ...
  [72 87 65]
  [59 92 61]
  [56 89 58]]

 [[25 17 42]
  [29 17 50]
  [29 16 55]
  ...
  [77 92 70]
  [64 97 66]
  [61 94 63]]]
[[  0   0   0 ...   0 255 255]
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[[50 58 93]
  [41 50 83]
  [53 62 92]
  ...
  [54 62 54]
  [62 70 62]
  [36 44 36]]

 [[41 49 84]
  [43 52 85]
  [45 54 84]
  ...
  [63 71 63]
  [43 51 43]
  [40 48 40]]

 [[37 39 83]
  [51 52 90]
  [47 47 79]
  ...
  [64 69 66]
  [24 29 26]
  [40 45 42]]

 ...

 [[20 34 44]
  [20 31 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 3 73 83]
  [12 65 78]
  [24 63 77]
  ...
  [69 78 80]
  [67 73 75]
  [59 65 67]]

 [[ 0 68 78]
  [ 8 61 74]
  [21 60 74]
  ...
  [65 74 76]
  [67 73 75]
  [65 71 73]]

 [[16 63 69]
  [28 62 70]
  [44 65 77]
  ...
  [64 71 73]
  [59 66 68]
  [58 65 67]]

 ...

 [[14 12 54]
  [18 21 42]
  [18 27 29]
  ...
  [48 61 36]
  [47 63 27]
  [50 66 30]]

 [[19 24 45]
  [ 9 23 52]
  [ 0 22 58]
  ...
  [58 59 45]
  [60 58 48]
  [60 58 48]]

 [[23 28 49]
  [12 26 55]
  [ 1 23 59]
  ...
  [59 60 46]
  [63 61 51]
  [61 59 49]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[36 50 51]
  [50 72 70]
  [35 69 62]
  ...
  [60 73 69]
  [62 79 75]
  [51 68 64]]

 [[35 49 50]
  [45 67 65]
  [28 62 55]
  ...
  [63 76 72]
  [61 78 74]
  [47 64 60]]

 [[39 52 55]
  [43 63 64]
  [31 58 53]
  ...
  [72 76 76]
  [74 78

[[[41 57 76]
  [30 47 63]
  [51 68 83]
  ...
  [13 19 12]
  [12 18 10]
  [12 18 10]]

 [[36 52 71]
  [35 52 68]
  [50 67 82]
  ...
  [12 18 11]
  [12 18 10]
  [11 17  9]]

 [[40 53 76]
  [43 56 79]
  [45 61 81]
  ...
  [20 14 11]
  [20 15  9]
  [19 14  8]]

 ...

 [[19 25 28]
  [24 29 35]
  [25 30 37]
  ...
  [81 84 70]
  [76 79 57]
  [76 79 57]]

 [[25 26 22]
  [28 30 30]
  [26 32 35]
  ...
  [84 82 64]
  [79 81 45]
  [76 78 42]]

 [[23 24 20]
  [25 27 27]
  [23 29 32]
  ...
  [85 83 65]
  [84 86 50]
  [81 83 47]]]
[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[[50 53 92]
  [47 51 85]
  [46 52 79]
  ...
  [19 18 32]
  [20 19 33]
  [20 19 33]]

 [[53 56 95]
  [49 53 87]
  [45 51 78]
  ...
  [23 22 36]
  [22 21 35]
  [19 18 32]]

 [[41 61 87]
  [41 60 80]
  [37 58 72]
  ...
  [20 27 26]
  [19 26 23]
  [15 22 19]]

 ...

 [[16 23 43]
  [15 24 

[[[ 7 63 83]
  [16 64 81]
  [19 60 74]
  ...
  [41 68 62]
  [52 84 77]
  [41 73 66]]

 [[ 1 57 77]
  [12 60 77]
  [18 59 73]
  ...
  [41 68 62]
  [49 81 74]
  [41 73 66]]

 [[ 0 66 76]
  [ 2 69 74]
  [ 6 68 70]
  ...
  [53 69 70]
  [54 74 75]
  [49 69 70]]

 ...

 [[22 22 30]
  [24 24 34]
  [24 24 34]
  ...
  [70 66 52]
  [64 60 46]
  [66 62 48]]

 [[26 19 50]
  [25 20 51]
  [22 19 50]
  ...
  [68 66 58]
  [58 61 49]
  [63 66 54]]

 [[28 21 52]
  [25 20 51]
  [21 18 49]
  ...
  [60 58 50]
  [48 51 39]
  [58 61 49]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 7 63 83]
  [16 64 81]
  [19 60 74]
  ...
  [41 68 62]
  [52 84 77]
  [41 73 66]]

 [[ 1 57 77]
  [12 60 77]
  [18 59 73]
  ...
  [41 68 62]
  [49 81 74]
  [41 73 66]]

 [[ 0 66 76]
  [ 2 69 74]
  [ 6 68 70]
  ...
  [53 69 70]
  [54 74 75]
  [49 69 70]]

 ...

 [[22 22 30]
  [24 24 34]
  [24 24 34]
  ...
  [70 66 52]
  [64 60 46]
  [66 62 48]]

 [[26 19

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[49 58 71]
  [58 65 76]
  [54 62 69]
  ...
  [63 67 67]
  [65 67 67]
  [66 68 68]]

 [[45 54 67]
  [55 62 73]
  [54 62 69]
  ...
  [65 69 69]
  [67 69 69]
  [66 68 68]]

 [[42 54 73]
  [52 60 76]
  [55 62 73]
  ...
  [64 72 71]
  [63 71 70]
  [62 70 69]]

 ...

 [[22 29 32]
  [28 31 45]
  [29 30 52]
  ...
  [69 82 69]
  [71 81 72]
  [66 76 67]]

 [[20 22 22]
  [22 16 41]
  [21 10 57]
  ...
  [66 75 70]
  [65 73 72]
  [61 69 68]]

 [[38 40 40]
  [33 27 52]
  [26 15 62]
  ...
  [63 72 67]
  [64 72 71]
  [63 71 70]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[49 67 82]
  [42 58 77]
  [52 65 88]
  ...
  [68 68 78]
  [65 65 75]
  [67 67 77]]

 [[41 59 74]
  [40 56 75]
  [50 63 86]
  ...
  [68 68 78]
  [65 65 75]
  [69 69 79]]

 [[45 61 71]
  [43 60 75]
  [44 62 78]
  ...
  [68 69 73]
  [63 64

[[[33 66 63]
  [39 68 63]
  [42 68 59]
  ...
  [57 51 59]
  [74 64 75]
  [79 69 80]]

 [[32 65 62]
  [38 67 62]
  [42 68 59]
  ...
  [66 60 68]
  [80 70 81]
  [81 71 82]]

 [[38 56 80]
  [43 59 79]
  [45 59 76]
  ...
  [53 70 68]
  [61 78 76]
  [58 75 73]]

 ...

 [[23 23 33]
  [14 20 37]
  [ 6 19 42]
  ...
  [62 58 58]
  [57 49 50]
  [68 60 61]]

 [[23 22 36]
  [13 23 42]
  [ 2 22 46]
  ...
  [63 63 65]
  [62 55 59]
  [75 68 72]]

 [[32 31 45]
  [23 33 52]
  [10 30 54]
  ...
  [60 60 62]
  [55 48 52]
  [69 62 66]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[33 66 63]
  [39 68 63]
  [42 68 59]
  ...
  [57 51 59]
  [74 64 75]
  [79 69 80]]

 [[32 65 62]
  [38 67 62]
  [42 68 59]
  ...
  [66 60 68]
  [80 70 81]
  [81 71 82]]

 [[38 56 80]
  [43 59 79]
  [45 59 76]
  ...
  [53 70 68]
  [61 78 76]
  [58 75 73]]

 ...

 [[23 23 33]
  [14 20 37]
  [ 6 19 42]
  ...
  [62 58 58]
  [57 49 50]
  [68 60 61]]

 [[23 22

[[[13 57 83]
  [25 54 77]
  [42 56 75]
  ...
  [38 37 41]
  [23 32 35]
  [24 33 36]]

 [[13 57 83]
  [25 54 77]
  [43 57 76]
  ...
  [39 38 42]
  [24 33 36]
  [22 31 34]]

 [[36 58 74]
  [35 53 68]
  [37 55 65]
  ...
  [47 34 39]
  [45 30 35]
  [46 31 36]]

 ...

 [[22 24 34]
  [25 27 37]
  [24 26 36]
  ...
  [61 77 68]
  [49 63 54]
  [21 35 26]]

 [[12 21 42]
  [17 24 44]
  [17 23 39]
  ...
  [75 72 75]
  [61 56 59]
  [42 37 40]]

 [[11 20 41]
  [14 21 41]
  [13 19 35]
  ...
  [66 63 66]
  [57 52 55]
  [56 51 54]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[45 53 69]
  [49 64 77]
  [39 63 72]
  ...
  [53 46 58]
  [56 43 56]
  [64 51 64]]

 [[47 55 71]
  [48 63 76]
  [41 65 74]
  ...
  [57 50 62]
  [61 48 61]
  [63 50 63]]

 [[36 57 79]
  [30 60 79]
  [25 63 80]
  ...
  [70 51 55]
  [80 53 58]
  [78 51 56]]

 ...

 [[68 15 30]
  [46 20 30]
  [23 26 32]
  ...
  [71 82 63]
  [66 81 59]
  [61 76 54]]

 [[45 19

[[[ 65  63  80]
  [ 54  54  82]
  [ 47  50  89]
  ...
  [ 68  67  73]
  [ 68  67  73]
  [ 71  70  76]]

 [[ 59  57  74]
  [ 52  52  80]
  [ 49  52  91]
  ...
  [ 70  69  75]
  [ 71  70  76]
  [ 73  72  78]]

 [[ 51  59  58]
  [ 52  56  70]
  [ 53  57  82]
  ...
  [ 72  77  74]
  [ 73  78  74]
  [ 72  77  73]]

 ...

 [[ 20  21  35]
  [ 22  22  30]
  [ 23  25  27]
  ...
  [ 90  91  79]
  [ 89  89  79]
  [ 79  79  69]]

 [[ 22  19  43]
  [ 25  19  45]
  [ 28  20  46]
  ...
  [103 104  90]
  [ 99 111  88]
  [ 93 105  82]]

 [[ 22  19  43]
  [ 25  19  45]
  [ 27  19  45]
  ...
  [ 95  96  82]
  [ 98 110  87]
  [ 97 109  86]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 65  63  80]
  [ 54  54  82]
  [ 47  50  89]
  ...
  [ 68  67  73]
  [ 68  67  73]
  [ 71  70  76]]

 [[ 59  57  74]
  [ 52  52  80]
  [ 49  52  91]
  ...
  [ 70  69  75]
  [ 71  70  76]
  [ 73  72  78]]

 [[ 51  59  58]
  [ 52  56  70]
  [ 53  57

[[[28 70 80]
  [37 73 81]
  [31 64 69]
  ...
  [64 69 65]
  [64 70 63]
  [65 71 64]]

 [[22 64 74]
  [32 68 76]
  [29 62 67]
  ...
  [63 68 64]
  [63 69 62]
  [64 70 63]]

 [[30 60 69]
  [39 65 74]
  [41 63 71]
  ...
  [62 70 67]
  [59 70 65]
  [60 71 66]]

 ...

 [[27 26 30]
  [26 23 37]
  [23 20 44]
  ...
  [87 92 71]
  [93 96 72]
  [93 96 72]]

 [[15 18 56]
  [11 16 64]
  [ 6 15 70]
  ...
  [81 84 80]
  [86 87 81]
  [86 87 81]]

 [[19 22 60]
  [14 19 67]
  [ 8 17 72]
  ...
  [80 83 79]
  [81 82 76]
  [82 83 77]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[28 70 80]
  [37 73 81]
  [31 64 69]
  ...
  [64 69 65]
  [64 70 63]
  [65 71 64]]

 [[22 64 74]
  [32 68 76]
  [29 62 67]
  ...
  [63 68 64]
  [63 69 62]
  [64 70 63]]

 [[30 60 69]
  [39 65 74]
  [41 63 71]
  ...
  [62 70 67]
  [59 70 65]
  [60 71 66]]

 ...

 [[27 26 30]
  [26 23 37]
  [23 20 44]
  ...
  [87 92 71]
  [93 96 72]
  [93 96 72]]

 [[15 18

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[ 7 62 59]
  [17 58 64]
  [35 62 76]
  ...
  [43 75 78]
  [13 57 57]
  [ 6 50 50]]

 [[11 66 63]
  [19 60 66]
  [31 58 72]
  ...
  [34 66 69]
  [15 59 59]
  [ 7 51 51]]

 [[11 61 78]
  [15 57 77]
  [22 54 77]
  ...
  [49 56 55]
  [52 60 57]
  [45 53 50]]

 ...

 [[16 17 33]
  [20 19 31]
  [23 21 29]
  ...
  [37 54 52]
  [37 56 54]
  [39 58 56]]

 [[39 17 43]
  [20 15 64]
  [ 0 12 81]
  ...
  [56 48 55]
  [59 53 60]
  [64 58 65]]

 [[43 21 47]
  [24 19 68]
  [ 3 15 84]
  ...
  [62 54 61]
  [62 56 63]
  [57 51 58]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[23 55 80]
  [32 61 86]
  [33 58 81]
  ...
  [36 34 34]
  [31 34 31]
  [32 35 32]]

 [[22 54 79]
  [27 56 81]
  [30 55 78]
  ...
  [35 33 33]
  [32 35 32]
  [34 37 34]]

 [[47 61 71]
  [48 57 68]
  [47 55 64]
  ...
  [40 40 40]
  [37 40

In [2]:
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3)); 
  
# creating object 
fgbg = cv2.bgsegm.createBackgroundSubtractorGMG(); 
  
# capture frames from a camera  
cap = cv2.VideoCapture(0); 
while(1): 
    # read frames 
    ret, img = cap.read(); 
      
    # apply mask for background subtraction 
    fgmask = fgbg.apply(img); 
      
    # with noise frame 
    cv2.imshow('GMG noise', fgmask); 
      
    # apply transformation to remove noise 
    fgmask = cv2.morphologyEx(fgmask, cv2.MORPH_OPEN, kernel); 
      
    # after removing noise 
    cv2.imshow('GMG', fgmask); 
      
    key = cv2.waitKey(1)
    if  key == ord('q'):
        break
        
cap.release(); 
cv2.destroyAllWindows();